// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.0-devel
// 	protoc        v3.11.4
// source: proto/blog.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Blog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Blog) Reset() {
	*x = Blog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0}
}

type Blog_LastArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id статьи
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// название
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// автор
	User *Common_UserLink `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// дата создания
	Date *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Blog_LastArticle) Reset() {
	*x = Blog_LastArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_LastArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_LastArticle) ProtoMessage() {}

func (x *Blog_LastArticle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_LastArticle.ProtoReflect.Descriptor instead.
func (*Blog_LastArticle) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Blog_LastArticle) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Blog_LastArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blog_LastArticle) GetUser() *Common_UserLink {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Blog_LastArticle) GetDate() *timestamp.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type Blog_Community struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id рубрики
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// название
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// описание
	CommunityDescription string `protobuf:"bytes,3,opt,name=community_description,json=communityDescription,proto3" json:"community_description,omitempty"`
	// правила
	Rules string `protobuf:"bytes,4,opt,name=rules,proto3" json:"rules,omitempty"`
	// аватар
	Avatar string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// статистика
	Stats *Blog_Community_Stats `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	// последняя статья
	LastArticle *Blog_LastArticle `protobuf:"bytes,7,opt,name=last_article,json=lastArticle,proto3" json:"last_article,omitempty"`
}

func (x *Blog_Community) Reset() {
	*x = Blog_Community{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_Community) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_Community) ProtoMessage() {}

func (x *Blog_Community) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_Community.ProtoReflect.Descriptor instead.
func (*Blog_Community) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Blog_Community) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Blog_Community) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blog_Community) GetCommunityDescription() string {
	if x != nil {
		return x.CommunityDescription
	}
	return ""
}

func (x *Blog_Community) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

func (x *Blog_Community) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Blog_Community) GetStats() *Blog_Community_Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Blog_Community) GetLastArticle() *Blog_LastArticle {
	if x != nil {
		return x.LastArticle
	}
	return nil
}

type Blog_Article struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id статьи
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// название
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// данные о создании
	Creation *Common_Creation `protobuf:"bytes,3,opt,name=creation,proto3" json:"creation,omitempty"`
	// текст
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// теги
	Tags string `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	// статистика
	Stats *Blog_Article_Stats `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *Blog_Article) Reset() {
	*x = Blog_Article{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_Article) ProtoMessage() {}

func (x *Blog_Article) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_Article.ProtoReflect.Descriptor instead.
func (*Blog_Article) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Blog_Article) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Blog_Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blog_Article) GetCreation() *Common_Creation {
	if x != nil {
		return x.Creation
	}
	return nil
}

func (x *Blog_Article) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Blog_Article) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Blog_Article) GetStats() *Blog_Article_Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Blog_Blog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id блога
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// автор
	User *Common_UserLink `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// блог закрыт?
	IsClosed bool `protobuf:"varint,3,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	// статистика
	Stats *Blog_Blog_Stats `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	// последняя статья
	LastArticle *Blog_LastArticle `protobuf:"bytes,5,opt,name=last_article,json=lastArticle,proto3" json:"last_article,omitempty"`
}

func (x *Blog_Blog) Reset() {
	*x = Blog_Blog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_Blog) ProtoMessage() {}

func (x *Blog_Blog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_Blog.ProtoReflect.Descriptor instead.
func (*Blog_Blog) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Blog_Blog) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Blog_Blog) GetUser() *Common_UserLink {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Blog_Blog) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

func (x *Blog_Blog) GetStats() *Blog_Blog_Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Blog_Blog) GetLastArticle() *Blog_LastArticle {
	if x != nil {
		return x.LastArticle
	}
	return nil
}

type Blog_Comment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id сообщения
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// данные о создании
	Creation *Common_Creation `protobuf:"bytes,2,opt,name=creation,proto3" json:"creation,omitempty"`
	// текст сообщения
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// текст изъят модератором?
	IsCensored bool `protobuf:"varint,4,opt,name=is_censored,json=isCensored,proto3" json:"is_censored,omitempty"`
	// ответы на комментарий
	Answers []*Blog_Comment `protobuf:"bytes,5,rep,name=answers,proto3" json:"answers,omitempty"`
}

func (x *Blog_Comment) Reset() {
	*x = Blog_Comment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_Comment) ProtoMessage() {}

func (x *Blog_Comment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_Comment.ProtoReflect.Descriptor instead.
func (*Blog_Comment) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Blog_Comment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Blog_Comment) GetCreation() *Common_Creation {
	if x != nil {
		return x.Creation
	}
	return nil
}

func (x *Blog_Comment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Blog_Comment) GetIsCensored() bool {
	if x != nil {
		return x.IsCensored
	}
	return false
}

func (x *Blog_Comment) GetAnswers() []*Blog_Comment {
	if x != nil {
		return x.Answers
	}
	return nil
}

type Blog_CommunitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// основные рубрики
	Main []*Blog_Community `protobuf:"bytes,1,rep,name=main,proto3" json:"main,omitempty"`
	// дополнительные рубрики
	Additional []*Blog_Community `protobuf:"bytes,2,rep,name=additional,proto3" json:"additional,omitempty"`
}

func (x *Blog_CommunitiesResponse) Reset() {
	*x = Blog_CommunitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_CommunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_CommunitiesResponse) ProtoMessage() {}

func (x *Blog_CommunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_CommunitiesResponse.ProtoReflect.Descriptor instead.
func (*Blog_CommunitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Blog_CommunitiesResponse) GetMain() []*Blog_Community {
	if x != nil {
		return x.Main
	}
	return nil
}

func (x *Blog_CommunitiesResponse) GetAdditional() []*Blog_Community {
	if x != nil {
		return x.Additional
	}
	return nil
}

type Blog_CommunityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// рубрика
	Community *Blog_Community `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	// модераторы
	Moderators []*Common_UserLink `protobuf:"bytes,2,rep,name=moderators,proto3" json:"moderators,omitempty"`
	// авторы
	Authors []*Common_UserLink `protobuf:"bytes,3,rep,name=authors,proto3" json:"authors,omitempty"`
	// статьи
	Articles []*Blog_Article `protobuf:"bytes,4,rep,name=articles,proto3" json:"articles,omitempty"`
	// страницы
	Pages *Common_Pages `protobuf:"bytes,5,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *Blog_CommunityResponse) Reset() {
	*x = Blog_CommunityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_CommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_CommunityResponse) ProtoMessage() {}

func (x *Blog_CommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_CommunityResponse.ProtoReflect.Descriptor instead.
func (*Blog_CommunityResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Blog_CommunityResponse) GetCommunity() *Blog_Community {
	if x != nil {
		return x.Community
	}
	return nil
}

func (x *Blog_CommunityResponse) GetModerators() []*Common_UserLink {
	if x != nil {
		return x.Moderators
	}
	return nil
}

func (x *Blog_CommunityResponse) GetAuthors() []*Common_UserLink {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Blog_CommunityResponse) GetArticles() []*Blog_Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *Blog_CommunityResponse) GetPages() *Common_Pages {
	if x != nil {
		return x.Pages
	}
	return nil
}

type Blog_BlogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// блоги
	Blogs []*Blog_Blog `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	// страницы
	Pages *Common_Pages `protobuf:"bytes,2,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *Blog_BlogsResponse) Reset() {
	*x = Blog_BlogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_BlogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_BlogsResponse) ProtoMessage() {}

func (x *Blog_BlogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_BlogsResponse.ProtoReflect.Descriptor instead.
func (*Blog_BlogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Blog_BlogsResponse) GetBlogs() []*Blog_Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

func (x *Blog_BlogsResponse) GetPages() *Common_Pages {
	if x != nil {
		return x.Pages
	}
	return nil
}

type Blog_BlogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// статьи
	Articles []*Blog_Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	// страницы
	Pages *Common_Pages `protobuf:"bytes,2,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *Blog_BlogResponse) Reset() {
	*x = Blog_BlogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_BlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_BlogResponse) ProtoMessage() {}

func (x *Blog_BlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_BlogResponse.ProtoReflect.Descriptor instead.
func (*Blog_BlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Blog_BlogResponse) GetArticles() []*Blog_Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *Blog_BlogResponse) GetPages() *Common_Pages {
	if x != nil {
		return x.Pages
	}
	return nil
}

type Blog_BlogArticleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// статья
	Article *Blog_Article `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
}

func (x *Blog_BlogArticleResponse) Reset() {
	*x = Blog_BlogArticleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_BlogArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_BlogArticleResponse) ProtoMessage() {}

func (x *Blog_BlogArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_BlogArticleResponse.ProtoReflect.Descriptor instead.
func (*Blog_BlogArticleResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Blog_BlogArticleResponse) GetArticle() *Blog_Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type Blog_BlogArticleLikeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// количество лайков
	LikeCount uint64 `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
}

func (x *Blog_BlogArticleLikeResponse) Reset() {
	*x = Blog_BlogArticleLikeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_BlogArticleLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_BlogArticleLikeResponse) ProtoMessage() {}

func (x *Blog_BlogArticleLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_BlogArticleLikeResponse.ProtoReflect.Descriptor instead.
func (*Blog_BlogArticleLikeResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Blog_BlogArticleLikeResponse) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type Blog_BlogArticleCommentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// список комментариев
	Comments []*Blog_Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	// общее ко-во комментариев у поста
	TotalCount uint64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *Blog_BlogArticleCommentsResponse) Reset() {
	*x = Blog_BlogArticleCommentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_BlogArticleCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_BlogArticleCommentsResponse) ProtoMessage() {}

func (x *Blog_BlogArticleCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_BlogArticleCommentsResponse.ProtoReflect.Descriptor instead.
func (*Blog_BlogArticleCommentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 11}
}

func (x *Blog_BlogArticleCommentsResponse) GetComments() []*Blog_Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *Blog_BlogArticleCommentsResponse) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Blog_Community_Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// количество статей
	ArticleCount uint64 `protobuf:"varint,1,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	// количество подписчиков
	SubscriberCount uint64 `protobuf:"varint,2,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
}

func (x *Blog_Community_Stats) Reset() {
	*x = Blog_Community_Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_Community_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_Community_Stats) ProtoMessage() {}

func (x *Blog_Community_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_Community_Stats.ProtoReflect.Descriptor instead.
func (*Blog_Community_Stats) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Blog_Community_Stats) GetArticleCount() uint64 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

func (x *Blog_Community_Stats) GetSubscriberCount() uint64 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

type Blog_Article_Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// количество лайков
	LikeCount uint64 `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	// количество просмотров
	ViewCount uint64 `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	// количество комментариев
	CommentCount uint64 `protobuf:"varint,3,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
}

func (x *Blog_Article_Stats) Reset() {
	*x = Blog_Article_Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_Article_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_Article_Stats) ProtoMessage() {}

func (x *Blog_Article_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_Article_Stats.ProtoReflect.Descriptor instead.
func (*Blog_Article_Stats) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Blog_Article_Stats) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Blog_Article_Stats) GetViewCount() uint64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Blog_Article_Stats) GetCommentCount() uint64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

type Blog_Blog_Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// количество статей
	ArticleCount uint64 `protobuf:"varint,1,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	// количество подписчиков
	SubscriberCount uint64 `protobuf:"varint,2,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
}

func (x *Blog_Blog_Stats) Reset() {
	*x = Blog_Blog_Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_blog_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Blog_Blog_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog_Blog_Stats) ProtoMessage() {}

func (x *Blog_Blog_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog_Blog_Stats.ProtoReflect.Descriptor instead.
func (*Blog_Blog_Stats) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *Blog_Blog_Stats) GetArticleCount() uint64 {
	if x != nil {
		return x.ArticleCount
	}
	return 0
}

func (x *Blog_Blog_Stats) GetSubscriberCount() uint64 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

var File_proto_blog_proto protoreflect.FileDescriptor

var file_proto_blog_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x0f, 0x0a, 0x04, 0x42, 0x6c, 0x6f, 0x67,
	0x1a, 0x89, 0x01, 0x0a, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x1a, 0xd0, 0x02, 0x0a,
	0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x33, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x34, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x4c, 0x61,
	0x73, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x1a, 0x57, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a,
	0x9c, 0x02, 0x0a, 0x07, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x2c, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x1a, 0x6a, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x6c,
	0x69, 0x6b, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69,
	0x65, 0x77, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x76, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x90,
	0x02, 0x0a, 0x04, 0x42, 0x6c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x73, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x6c, 0x6f, 0x67,
	0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x34, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e,
	0x4c, 0x61, 0x73, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x0b, 0x6c, 0x61, 0x73,
	0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x1a, 0x57, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x1a, 0xa5, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a,
	0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x63, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x43, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x65, 0x64,
	0x12, 0x27, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x73, 0x1a, 0x6b, 0x0a, 0x13, 0x43, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x2f, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x42, 0x6c, 0x6f, 0x67,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x1a, 0xf0, 0x01, 0x0a, 0x11, 0x43, 0x6f, 0x6d, 0x6d, 0x75,
	0x6e, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79,
	0x52, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x12, 0x30, 0x0a, 0x0a, 0x6d,
	0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e,
	0x6b, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x2a, 0x0a,
	0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b,
	0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x61, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6c,
	0x6f, 0x67, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x08, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x56, 0x0a, 0x0d, 0x42, 0x6c, 0x6f,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x62, 0x6c,
	0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x42, 0x6c, 0x6f, 0x67,
	0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x23, 0x0a, 0x05,
	0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65,
	0x73, 0x1a, 0x5e, 0x0a, 0x0c, 0x42, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x29, 0x0a, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6c, 0x6f, 0x67, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x52, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x05,
	0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65,
	0x73, 0x1a, 0x3e, 0x0a, 0x13, 0x42, 0x6c, 0x6f, 0x67, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x61, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x6c, 0x6f, 0x67,
	0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x07, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x1a, 0x38, 0x0a, 0x17, 0x42, 0x6c, 0x6f, 0x67, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x6c, 0x69, 0x6b, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x69, 0x0a, 0x1b, 0x42,
	0x6c, 0x6f, 0x67, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42,
	0x6c, 0x6f, 0x67, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0c, 0x5a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_blog_proto_rawDescOnce sync.Once
	file_proto_blog_proto_rawDescData = file_proto_blog_proto_rawDesc
)

func file_proto_blog_proto_rawDescGZIP() []byte {
	file_proto_blog_proto_rawDescOnce.Do(func() {
		file_proto_blog_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_blog_proto_rawDescData)
	})
	return file_proto_blog_proto_rawDescData
}

var file_proto_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_blog_proto_goTypes = []interface{}{
	(*Blog)(nil),                             // 0: Blog
	(*Blog_LastArticle)(nil),                 // 1: Blog.LastArticle
	(*Blog_Community)(nil),                   // 2: Blog.Community
	(*Blog_Article)(nil),                     // 3: Blog.Article
	(*Blog_Blog)(nil),                        // 4: Blog.Blog
	(*Blog_Comment)(nil),                     // 5: Blog.Comment
	(*Blog_CommunitiesResponse)(nil),         // 6: Blog.CommunitiesResponse
	(*Blog_CommunityResponse)(nil),           // 7: Blog.CommunityResponse
	(*Blog_BlogsResponse)(nil),               // 8: Blog.BlogsResponse
	(*Blog_BlogResponse)(nil),                // 9: Blog.BlogResponse
	(*Blog_BlogArticleResponse)(nil),         // 10: Blog.BlogArticleResponse
	(*Blog_BlogArticleLikeResponse)(nil),     // 11: Blog.BlogArticleLikeResponse
	(*Blog_BlogArticleCommentsResponse)(nil), // 12: Blog.BlogArticleCommentsResponse
	(*Blog_Community_Stats)(nil),             // 13: Blog.Community.Stats
	(*Blog_Article_Stats)(nil),               // 14: Blog.Article.Stats
	(*Blog_Blog_Stats)(nil),                  // 15: Blog.Blog.Stats
	(*Common_UserLink)(nil),                  // 16: Common.UserLink
	(*timestamp.Timestamp)(nil),              // 17: google.protobuf.Timestamp
	(*Common_Creation)(nil),                  // 18: Common.Creation
	(*Common_Pages)(nil),                     // 19: Common.Pages
}
var file_proto_blog_proto_depIdxs = []int32{
	16, // 0: Blog.LastArticle.user:type_name -> Common.UserLink
	17, // 1: Blog.LastArticle.date:type_name -> google.protobuf.Timestamp
	13, // 2: Blog.Community.stats:type_name -> Blog.Community.Stats
	1,  // 3: Blog.Community.last_article:type_name -> Blog.LastArticle
	18, // 4: Blog.Article.creation:type_name -> Common.Creation
	14, // 5: Blog.Article.stats:type_name -> Blog.Article.Stats
	16, // 6: Blog.Blog.user:type_name -> Common.UserLink
	15, // 7: Blog.Blog.stats:type_name -> Blog.Blog.Stats
	1,  // 8: Blog.Blog.last_article:type_name -> Blog.LastArticle
	18, // 9: Blog.Comment.creation:type_name -> Common.Creation
	5,  // 10: Blog.Comment.answers:type_name -> Blog.Comment
	2,  // 11: Blog.CommunitiesResponse.main:type_name -> Blog.Community
	2,  // 12: Blog.CommunitiesResponse.additional:type_name -> Blog.Community
	2,  // 13: Blog.CommunityResponse.community:type_name -> Blog.Community
	16, // 14: Blog.CommunityResponse.moderators:type_name -> Common.UserLink
	16, // 15: Blog.CommunityResponse.authors:type_name -> Common.UserLink
	3,  // 16: Blog.CommunityResponse.articles:type_name -> Blog.Article
	19, // 17: Blog.CommunityResponse.pages:type_name -> Common.Pages
	4,  // 18: Blog.BlogsResponse.blogs:type_name -> Blog.Blog
	19, // 19: Blog.BlogsResponse.pages:type_name -> Common.Pages
	3,  // 20: Blog.BlogResponse.articles:type_name -> Blog.Article
	19, // 21: Blog.BlogResponse.pages:type_name -> Common.Pages
	3,  // 22: Blog.BlogArticleResponse.article:type_name -> Blog.Article
	5,  // 23: Blog.BlogArticleCommentsResponse.comments:type_name -> Blog.Comment
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_blog_proto_init() }
func file_proto_blog_proto_init() {
	if File_proto_blog_proto != nil {
		return
	}
	file_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_blog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_LastArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_Community); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_Article); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_Blog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_Comment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_CommunitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_CommunityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_BlogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_BlogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_BlogArticleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_BlogArticleLikeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_BlogArticleCommentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_Community_Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_Article_Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_blog_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Blog_Blog_Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_blog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_blog_proto_goTypes,
		DependencyIndexes: file_proto_blog_proto_depIdxs,
		MessageInfos:      file_proto_blog_proto_msgTypes,
	}.Build()
	File_proto_blog_proto = out.File
	file_proto_blog_proto_rawDesc = nil
	file_proto_blog_proto_goTypes = nil
	file_proto_blog_proto_depIdxs = nil
}
