// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1-devel
// 	protoc        v3.11.4
// source: proto/bookcase.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Bookcase_BookcaseType int32

const (
	Bookcase_BOOKCASE_TYPE_UNKNOWN Bookcase_BookcaseType = 0
	// Прочитать
	Bookcase_BOOKCASE_TYPE_READ Bookcase_BookcaseType = 1
	// Ожидаю
	Bookcase_BOOKCASE_TYPE_WAIT Bookcase_BookcaseType = 2
	// Куплю
	Bookcase_BOOKCASE_TYPE_BUY Bookcase_BookcaseType = 3
	// Продам
	Bookcase_BOOKCASE_TYPE_SALE Bookcase_BookcaseType = 4
	// Прочее
	Bookcase_BOOKCASE_TYPE_FREE Bookcase_BookcaseType = 5
)

// Enum value maps for Bookcase_BookcaseType.
var (
	Bookcase_BookcaseType_name = map[int32]string{
		0: "BOOKCASE_TYPE_UNKNOWN",
		1: "BOOKCASE_TYPE_READ",
		2: "BOOKCASE_TYPE_WAIT",
		3: "BOOKCASE_TYPE_BUY",
		4: "BOOKCASE_TYPE_SALE",
		5: "BOOKCASE_TYPE_FREE",
	}
	Bookcase_BookcaseType_value = map[string]int32{
		"BOOKCASE_TYPE_UNKNOWN": 0,
		"BOOKCASE_TYPE_READ":    1,
		"BOOKCASE_TYPE_WAIT":    2,
		"BOOKCASE_TYPE_BUY":     3,
		"BOOKCASE_TYPE_SALE":    4,
		"BOOKCASE_TYPE_FREE":    5,
	}
)

func (x Bookcase_BookcaseType) Enum() *Bookcase_BookcaseType {
	p := new(Bookcase_BookcaseType)
	*p = x
	return p
}

func (x Bookcase_BookcaseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Bookcase_BookcaseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bookcase_proto_enumTypes[0].Descriptor()
}

func (Bookcase_BookcaseType) Type() protoreflect.EnumType {
	return &file_proto_bookcase_proto_enumTypes[0]
}

func (x Bookcase_BookcaseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Bookcase_BookcaseType.Descriptor instead.
func (Bookcase_BookcaseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 0}
}

type Bookcase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Bookcase) Reset() {
	*x = Bookcase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase) ProtoMessage() {}

func (x *Bookcase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase.ProtoReflect.Descriptor instead.
func (*Bookcase) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0}
}

type Bookcase_Bookcase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id книжной полки
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// приватная?
	IsPrivate bool `protobuf:"varint,2,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	// тип
	Type Bookcase_BookcaseType `protobuf:"varint,3,opt,name=type,proto3,enum=Bookcase_BookcaseType" json:"type,omitempty"`
	// название
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// комментарий
	Comment string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	// порядковый номер
	Index uint64 `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	// количество элементов
	ItemCount uint64 `protobuf:"varint,7,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
}

func (x *Bookcase_Bookcase) Reset() {
	*x = Bookcase_Bookcase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_Bookcase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_Bookcase) ProtoMessage() {}

func (x *Bookcase_Bookcase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_Bookcase.ProtoReflect.Descriptor instead.
func (*Bookcase_Bookcase) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Bookcase_Bookcase) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bookcase_Bookcase) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *Bookcase_Bookcase) GetType() Bookcase_BookcaseType {
	if x != nil {
		return x.Type
	}
	return Bookcase_BOOKCASE_TYPE_UNKNOWN
}

func (x *Bookcase_Bookcase) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bookcase_Bookcase) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Bookcase_Bookcase) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Bookcase_Bookcase) GetItemCount() uint64 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

type Bookcase_BookcaseBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// название блока
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// книжные полки
	Bookcases []*Bookcase_Bookcase `protobuf:"bytes,2,rep,name=bookcases,proto3" json:"bookcases,omitempty"`
}

func (x *Bookcase_BookcaseBlock) Reset() {
	*x = Bookcase_BookcaseBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_BookcaseBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_BookcaseBlock) ProtoMessage() {}

func (x *Bookcase_BookcaseBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_BookcaseBlock.ProtoReflect.Descriptor instead.
func (*Bookcase_BookcaseBlock) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Bookcase_BookcaseBlock) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bookcase_BookcaseBlock) GetBookcases() []*Bookcase_Bookcase {
	if x != nil {
		return x.Bookcases
	}
	return nil
}

type Bookcase_BookcaseBlocksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// список блоков книжных полок
	BookcaseBlocks []*Bookcase_BookcaseBlock `protobuf:"bytes,1,rep,name=bookcase_blocks,json=bookcaseBlocks,proto3" json:"bookcase_blocks,omitempty"`
}

func (x *Bookcase_BookcaseBlocksResponse) Reset() {
	*x = Bookcase_BookcaseBlocksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_BookcaseBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_BookcaseBlocksResponse) ProtoMessage() {}

func (x *Bookcase_BookcaseBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_BookcaseBlocksResponse.ProtoReflect.Descriptor instead.
func (*Bookcase_BookcaseBlocksResponse) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Bookcase_BookcaseBlocksResponse) GetBookcaseBlocks() []*Bookcase_BookcaseBlock {
	if x != nil {
		return x.BookcaseBlocks
	}
	return nil
}

type Bookcase_BookcaseInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id книжной полки
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// приватная?
	IsPrivate bool `protobuf:"varint,2,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	// тип
	Type Bookcase_BookcaseType `protobuf:"varint,3,opt,name=type,proto3,enum=Bookcase_BookcaseType" json:"type,omitempty"`
	// название
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// комментарий
	Comment string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *Bookcase_BookcaseInfo) Reset() {
	*x = Bookcase_BookcaseInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_BookcaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_BookcaseInfo) ProtoMessage() {}

func (x *Bookcase_BookcaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_BookcaseInfo.ProtoReflect.Descriptor instead.
func (*Bookcase_BookcaseInfo) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Bookcase_BookcaseInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bookcase_BookcaseInfo) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *Bookcase_BookcaseInfo) GetType() Bookcase_BookcaseType {
	if x != nil {
		return x.Type
	}
	return Bookcase_BOOKCASE_TYPE_UNKNOWN
}

func (x *Bookcase_BookcaseInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bookcase_BookcaseInfo) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Bookcase_Edition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id item-а на полке
	ItemId uint64 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// id издания
	Id uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// тип (авторская книга/сборник/etc; может отсутствовать, если не задан)
	Type EditionType `protobuf:"varint,3,opt,name=type,proto3,enum=EditionType" json:"type,omitempty"`
	// уровень проверенности
	CorrectnessLevel EditionCorrectnessLevel `protobuf:"varint,4,opt,name=correctness_level,json=correctnessLevel,proto3,enum=EditionCorrectnessLevel" json:"correctness_level,omitempty"`
	// URL обложки
	Cover string `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	// авторы
	Authors string `protobuf:"bytes,6,opt,name=authors,proto3" json:"authors,omitempty"`
	// название
	Title string `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	// год публикации
	Year uint64 `protobuf:"varint,8,opt,name=year,proto3" json:"year,omitempty"`
	// издательства
	Publishers string `protobuf:"bytes,9,opt,name=publishers,proto3" json:"publishers,omitempty"`
	// описание
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// планируемая дата издания (если издание еще не опубликовано)
	PlannedPublicationDate string `protobuf:"bytes,11,opt,name=planned_publication_date,json=plannedPublicationDate,proto3" json:"planned_publication_date,omitempty"`
	// предложения в магазинах
	Offers *Bookcase_Edition_Offers `protobuf:"bytes,12,opt,name=offers,proto3" json:"offers,omitempty"`
	// комментарий
	Comment string `protobuf:"bytes,13,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *Bookcase_Edition) Reset() {
	*x = Bookcase_Edition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_Edition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_Edition) ProtoMessage() {}

func (x *Bookcase_Edition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_Edition.ProtoReflect.Descriptor instead.
func (*Bookcase_Edition) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Bookcase_Edition) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Bookcase_Edition) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bookcase_Edition) GetType() EditionType {
	if x != nil {
		return x.Type
	}
	return EditionType_EDITION_TYPE_UNKNOWN
}

func (x *Bookcase_Edition) GetCorrectnessLevel() EditionCorrectnessLevel {
	if x != nil {
		return x.CorrectnessLevel
	}
	return EditionCorrectnessLevel_EDITION_CORRECTNESS_LEVEL_UNKNOWN
}

func (x *Bookcase_Edition) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Bookcase_Edition) GetAuthors() string {
	if x != nil {
		return x.Authors
	}
	return ""
}

func (x *Bookcase_Edition) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bookcase_Edition) GetYear() uint64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Bookcase_Edition) GetPublishers() string {
	if x != nil {
		return x.Publishers
	}
	return ""
}

func (x *Bookcase_Edition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bookcase_Edition) GetPlannedPublicationDate() string {
	if x != nil {
		return x.PlannedPublicationDate
	}
	return ""
}

func (x *Bookcase_Edition) GetOffers() *Bookcase_Edition_Offers {
	if x != nil {
		return x.Offers
	}
	return nil
}

func (x *Bookcase_Edition) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Bookcase_EditionBookcaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// информация о полке
	Bookcase *Bookcase_BookcaseInfo `protobuf:"bytes,1,opt,name=bookcase,proto3" json:"bookcase,omitempty"`
	// список изданий на полке
	Editions []*Bookcase_Edition `protobuf:"bytes,2,rep,name=editions,proto3" json:"editions,omitempty"`
	// страницы
	Pages *Common_Pages `protobuf:"bytes,3,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *Bookcase_EditionBookcaseResponse) Reset() {
	*x = Bookcase_EditionBookcaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_EditionBookcaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_EditionBookcaseResponse) ProtoMessage() {}

func (x *Bookcase_EditionBookcaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_EditionBookcaseResponse.ProtoReflect.Descriptor instead.
func (*Bookcase_EditionBookcaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Bookcase_EditionBookcaseResponse) GetBookcase() *Bookcase_BookcaseInfo {
	if x != nil {
		return x.Bookcase
	}
	return nil
}

func (x *Bookcase_EditionBookcaseResponse) GetEditions() []*Bookcase_Edition {
	if x != nil {
		return x.Editions
	}
	return nil
}

func (x *Bookcase_EditionBookcaseResponse) GetPages() *Common_Pages {
	if x != nil {
		return x.Pages
	}
	return nil
}

type Bookcase_Work struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id item-а на полке
	ItemId uint64 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// id произведения
	Id uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// тип (роман/сборник/etc; может отсутствовать)
	Type WorkType `protobuf:"varint,3,opt,name=type,proto3,enum=WorkType" json:"type,omitempty"`
	// авторы
	Authors []*Bookcase_Work_Author `protobuf:"bytes,4,rep,name=authors,proto3" json:"authors,omitempty"`
	// название на русском языке
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// название в оригинале
	OriginalTitle string `protobuf:"bytes,6,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	// альтернативные названия
	AlternativeTitles string `protobuf:"bytes,7,opt,name=alternative_titles,json=alternativeTitles,proto3" json:"alternative_titles,omitempty"`
	// примечание
	Note string `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
	// год
	Year int64 `protobuf:"varint,9,opt,name=year,proto3" json:"year,omitempty"`
	// описание
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// опубликовано?
	IsPublished bool `protobuf:"varint,11,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	// статистика
	Stats *Bookcase_Work_Stats `protobuf:"bytes,12,opt,name=stats,proto3" json:"stats,omitempty"`
	// персональное
	Own *Bookcase_Work_Own `protobuf:"bytes,13,opt,name=own,proto3" json:"own,omitempty"`
	// комментарий
	Comment string `protobuf:"bytes,14,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *Bookcase_Work) Reset() {
	*x = Bookcase_Work{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_Work) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_Work) ProtoMessage() {}

func (x *Bookcase_Work) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_Work.ProtoReflect.Descriptor instead.
func (*Bookcase_Work) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Bookcase_Work) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Bookcase_Work) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bookcase_Work) GetType() WorkType {
	if x != nil {
		return x.Type
	}
	return WorkType_WORK_TYPE_UNKNOWN
}

func (x *Bookcase_Work) GetAuthors() []*Bookcase_Work_Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

func (x *Bookcase_Work) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bookcase_Work) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *Bookcase_Work) GetAlternativeTitles() string {
	if x != nil {
		return x.AlternativeTitles
	}
	return ""
}

func (x *Bookcase_Work) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Bookcase_Work) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Bookcase_Work) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bookcase_Work) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *Bookcase_Work) GetStats() *Bookcase_Work_Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Bookcase_Work) GetOwn() *Bookcase_Work_Own {
	if x != nil {
		return x.Own
	}
	return nil
}

func (x *Bookcase_Work) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Bookcase_WorkBookcaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// информация о полке
	Bookcase *Bookcase_BookcaseInfo `protobuf:"bytes,1,opt,name=bookcase,proto3" json:"bookcase,omitempty"`
	// список произведений на полке
	Works []*Bookcase_Work `protobuf:"bytes,2,rep,name=works,proto3" json:"works,omitempty"`
	// страницы
	Pages *Common_Pages `protobuf:"bytes,3,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *Bookcase_WorkBookcaseResponse) Reset() {
	*x = Bookcase_WorkBookcaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_WorkBookcaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_WorkBookcaseResponse) ProtoMessage() {}

func (x *Bookcase_WorkBookcaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_WorkBookcaseResponse.ProtoReflect.Descriptor instead.
func (*Bookcase_WorkBookcaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Bookcase_WorkBookcaseResponse) GetBookcase() *Bookcase_BookcaseInfo {
	if x != nil {
		return x.Bookcase
	}
	return nil
}

func (x *Bookcase_WorkBookcaseResponse) GetWorks() []*Bookcase_Work {
	if x != nil {
		return x.Works
	}
	return nil
}

func (x *Bookcase_WorkBookcaseResponse) GetPages() *Common_Pages {
	if x != nil {
		return x.Pages
	}
	return nil
}

type Bookcase_Film struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id item-а на полке
	ItemId uint64 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	// id фильма
	Id uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// тип (фильм/сериал/etc; может отсутствовать, если не задан)
	Type FilmType `protobuf:"varint,3,opt,name=type,proto3,enum=FilmType" json:"type,omitempty"`
	// URL постера
	Poster string `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"`
	// название на русском языке
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// название в оригинале
	OriginalTitle string `protobuf:"bytes,6,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	// год выпуска (для всего, кроме сериалов)
	Year uint64 `protobuf:"varint,7,opt,name=year,proto3" json:"year,omitempty"`
	// год старта трансляции (для сериалов)
	StartYear uint64 `protobuf:"varint,8,opt,name=start_year,json=startYear,proto3" json:"start_year,omitempty"`
	// год окончания трансляции (для сериалов)
	EndYear uint64 `protobuf:"varint,9,opt,name=end_year,json=endYear,proto3" json:"end_year,omitempty"`
	// страны производства
	Countries string `protobuf:"bytes,10,opt,name=countries,proto3" json:"countries,omitempty"`
	// жанры
	Genres string `protobuf:"bytes,11,opt,name=genres,proto3" json:"genres,omitempty"`
	// режиссеры
	Directors string `protobuf:"bytes,12,opt,name=directors,proto3" json:"directors,omitempty"`
	// сценаристы
	ScreenWriters string `protobuf:"bytes,13,opt,name=screen_writers,json=screenWriters,proto3" json:"screen_writers,omitempty"`
	// актеры
	Actors string `protobuf:"bytes,14,opt,name=actors,proto3" json:"actors,omitempty"`
	// описание
	Description string `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	// комментарий
	Comment string `protobuf:"bytes,16,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *Bookcase_Film) Reset() {
	*x = Bookcase_Film{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_Film) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_Film) ProtoMessage() {}

func (x *Bookcase_Film) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_Film.ProtoReflect.Descriptor instead.
func (*Bookcase_Film) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Bookcase_Film) GetItemId() uint64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *Bookcase_Film) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bookcase_Film) GetType() FilmType {
	if x != nil {
		return x.Type
	}
	return FilmType_FILM_TYPE_UNKNOWN
}

func (x *Bookcase_Film) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *Bookcase_Film) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bookcase_Film) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *Bookcase_Film) GetYear() uint64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Bookcase_Film) GetStartYear() uint64 {
	if x != nil {
		return x.StartYear
	}
	return 0
}

func (x *Bookcase_Film) GetEndYear() uint64 {
	if x != nil {
		return x.EndYear
	}
	return 0
}

func (x *Bookcase_Film) GetCountries() string {
	if x != nil {
		return x.Countries
	}
	return ""
}

func (x *Bookcase_Film) GetGenres() string {
	if x != nil {
		return x.Genres
	}
	return ""
}

func (x *Bookcase_Film) GetDirectors() string {
	if x != nil {
		return x.Directors
	}
	return ""
}

func (x *Bookcase_Film) GetScreenWriters() string {
	if x != nil {
		return x.ScreenWriters
	}
	return ""
}

func (x *Bookcase_Film) GetActors() string {
	if x != nil {
		return x.Actors
	}
	return ""
}

func (x *Bookcase_Film) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bookcase_Film) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Bookcase_FilmBookcaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// информация о полке
	Bookcase *Bookcase_BookcaseInfo `protobuf:"bytes,1,opt,name=bookcase,proto3" json:"bookcase,omitempty"`
	// список фильмов на полке
	Films []*Bookcase_Film `protobuf:"bytes,2,rep,name=films,proto3" json:"films,omitempty"`
	// страницы
	Pages *Common_Pages `protobuf:"bytes,3,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *Bookcase_FilmBookcaseResponse) Reset() {
	*x = Bookcase_FilmBookcaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_FilmBookcaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_FilmBookcaseResponse) ProtoMessage() {}

func (x *Bookcase_FilmBookcaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_FilmBookcaseResponse.ProtoReflect.Descriptor instead.
func (*Bookcase_FilmBookcaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Bookcase_FilmBookcaseResponse) GetBookcase() *Bookcase_BookcaseInfo {
	if x != nil {
		return x.Bookcase
	}
	return nil
}

func (x *Bookcase_FilmBookcaseResponse) GetFilms() []*Bookcase_Film {
	if x != nil {
		return x.Films
	}
	return nil
}

func (x *Bookcase_FilmBookcaseResponse) GetPages() *Common_Pages {
	if x != nil {
		return x.Pages
	}
	return nil
}

type Bookcase_ItemCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// текст комментария
	Comment string `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *Bookcase_ItemCommentResponse) Reset() {
	*x = Bookcase_ItemCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_ItemCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_ItemCommentResponse) ProtoMessage() {}

func (x *Bookcase_ItemCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_ItemCommentResponse.ProtoReflect.Descriptor instead.
func (*Bookcase_ItemCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Bookcase_ItemCommentResponse) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Bookcase_Edition_Offers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// предложение на Озоне
	Ozon *Bookcase_Edition_Offers_Offer `protobuf:"bytes,1,opt,name=ozon,proto3" json:"ozon,omitempty"`
	// предложение на Лабиринте
	Labirint *Bookcase_Edition_Offers_Offer `protobuf:"bytes,2,opt,name=labirint,proto3" json:"labirint,omitempty"`
}

func (x *Bookcase_Edition_Offers) Reset() {
	*x = Bookcase_Edition_Offers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_Edition_Offers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_Edition_Offers) ProtoMessage() {}

func (x *Bookcase_Edition_Offers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_Edition_Offers.ProtoReflect.Descriptor instead.
func (*Bookcase_Edition_Offers) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *Bookcase_Edition_Offers) GetOzon() *Bookcase_Edition_Offers_Offer {
	if x != nil {
		return x.Ozon
	}
	return nil
}

func (x *Bookcase_Edition_Offers) GetLabirint() *Bookcase_Edition_Offers_Offer {
	if x != nil {
		return x.Labirint
	}
	return nil
}

type Bookcase_Edition_Offers_Offer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// URL предложения
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// цена
	Price uint64 `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Bookcase_Edition_Offers_Offer) Reset() {
	*x = Bookcase_Edition_Offers_Offer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_Edition_Offers_Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_Edition_Offers_Offer) ProtoMessage() {}

func (x *Bookcase_Edition_Offers_Offer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_Edition_Offers_Offer.ProtoReflect.Descriptor instead.
func (*Bookcase_Edition_Offers_Offer) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 4, 0, 0}
}

func (x *Bookcase_Edition_Offers_Offer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Bookcase_Edition_Offers_Offer) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Bookcase_Work_Author struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id автора
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// имя на русском языке
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// страница открыта?
	IsOpened bool `protobuf:"varint,3,opt,name=is_opened,json=isOpened,proto3" json:"is_opened,omitempty"`
}

func (x *Bookcase_Work_Author) Reset() {
	*x = Bookcase_Work_Author{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_Work_Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_Work_Author) ProtoMessage() {}

func (x *Bookcase_Work_Author) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_Work_Author.ProtoReflect.Descriptor instead.
func (*Bookcase_Work_Author) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 6, 0}
}

func (x *Bookcase_Work_Author) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bookcase_Work_Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bookcase_Work_Author) GetIsOpened() bool {
	if x != nil {
		return x.IsOpened
	}
	return false
}

type Bookcase_Work_Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// средняя оценка
	AverageMark float64 `protobuf:"fixed64,1,opt,name=average_mark,json=averageMark,proto3" json:"average_mark,omitempty"`
	// количество оценок
	MarkCount uint64 `protobuf:"varint,2,opt,name=mark_count,json=markCount,proto3" json:"mark_count,omitempty"`
	// количество отзывов
	ResponseCount uint64 `protobuf:"varint,3,opt,name=response_count,json=responseCount,proto3" json:"response_count,omitempty"`
}

func (x *Bookcase_Work_Stats) Reset() {
	*x = Bookcase_Work_Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_Work_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_Work_Stats) ProtoMessage() {}

func (x *Bookcase_Work_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_Work_Stats.ProtoReflect.Descriptor instead.
func (*Bookcase_Work_Stats) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 6, 1}
}

func (x *Bookcase_Work_Stats) GetAverageMark() float64 {
	if x != nil {
		return x.AverageMark
	}
	return 0
}

func (x *Bookcase_Work_Stats) GetMarkCount() uint64 {
	if x != nil {
		return x.MarkCount
	}
	return 0
}

func (x *Bookcase_Work_Stats) GetResponseCount() uint64 {
	if x != nil {
		return x.ResponseCount
	}
	return 0
}

type Bookcase_Work_Own struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// собственная оценка произведению
	Mark uint64 `protobuf:"varint,1,opt,name=mark,proto3" json:"mark,omitempty"`
	// опубликован отзыв?
	IsResponsePublished bool `protobuf:"varint,2,opt,name=is_response_published,json=isResponsePublished,proto3" json:"is_response_published,omitempty"`
}

func (x *Bookcase_Work_Own) Reset() {
	*x = Bookcase_Work_Own{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bookcase_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bookcase_Work_Own) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookcase_Work_Own) ProtoMessage() {}

func (x *Bookcase_Work_Own) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bookcase_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookcase_Work_Own.ProtoReflect.Descriptor instead.
func (*Bookcase_Work_Own) Descriptor() ([]byte, []int) {
	return file_proto_bookcase_proto_rawDescGZIP(), []int{0, 6, 2}
}

func (x *Bookcase_Work_Own) GetMark() uint64 {
	if x != nil {
		return x.Mark
	}
	return 0
}

func (x *Bookcase_Work_Own) GetIsResponsePublished() bool {
	if x != nil {
		return x.IsResponsePublished
	}
	return false
}

var File_proto_bookcase_proto protoreflect.FileDescriptor

var file_proto_bookcase_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xd2, 0x17, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65,
	0x1a, 0xca, 0x01, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x42, 0x6f, 0x6f,
	0x6b, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x57, 0x0a,
	0x0d, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61,
	0x73, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x52, 0x09, 0x62, 0x6f, 0x6f,
	0x6b, 0x63, 0x61, 0x73, 0x65, 0x73, 0x1a, 0x5a, 0x0a, 0x16, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61,
	0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x40, 0x0a, 0x0f, 0x62, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x63, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x0e, 0x62, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x73, 0x1a, 0x99, 0x01, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x63, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0xe9,
	0x04, 0x0a, 0x07, 0x45, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74,
	0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x45, 0x0a, 0x11, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74,
	0x6e, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x18, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x63,
	0x74, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x10, 0x63, 0x6f, 0x72, 0x72,
	0x65, 0x63, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x72, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x18, 0x70, 0x6c, 0x61, 0x6e,
	0x6e, 0x65, 0x64, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x70, 0x6c, 0x61, 0x6e,
	0x6e, 0x65, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x45, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0xa9,
	0x01, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x12, 0x32, 0x0a, 0x04, 0x6f, 0x7a, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61,
	0x73, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x73, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x04, 0x6f, 0x7a, 0x6f, 0x6e, 0x12, 0x3a, 0x0a,
	0x08, 0x6c, 0x61, 0x62, 0x69, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52,
	0x08, 0x6c, 0x61, 0x62, 0x69, 0x72, 0x69, 0x6e, 0x74, 0x1a, 0x2f, 0x0a, 0x05, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x1a, 0xa1, 0x01, 0x0a, 0x17, 0x45,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x63, 0x61,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63,
	0x61, 0x73, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x65, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x61, 0x67,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x1a, 0xd0,
	0x05, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x2f, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2d, 0x0a,
	0x12, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x61, 0x6c, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x79, 0x65, 0x61, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63,
	0x61, 0x73, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x03, 0x6f, 0x77, 0x6e, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x57, 0x6f,
	0x72, 0x6b, 0x2e, 0x4f, 0x77, 0x6e, 0x52, 0x03, 0x6f, 0x77, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x49, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64,
	0x1a, 0x70, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0b, 0x61, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x4d, 0x61, 0x72, 0x6b, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x1a, 0x4d, 0x0a, 0x03, 0x4f, 0x77, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x32, 0x0a,
	0x15, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x69, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x1a, 0x95, 0x01, 0x0a, 0x14, 0x57, 0x6f, 0x72, 0x6b, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x62, 0x6f,
	0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x05, 0x77, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x05, 0x77,
	0x6f, 0x72, 0x6b, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x1a, 0xc0, 0x03, 0x0a, 0x04, 0x46, 0x69,
	0x6c, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x46, 0x69, 0x6c, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x79,
	0x65, 0x61, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x79, 0x65, 0x61,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x59, 0x65,
	0x61, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x59, 0x65, 0x61, 0x72, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67,
	0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e,
	0x72, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x5f, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x72, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x95, 0x01, 0x0a,
	0x14, 0x46, 0x69, 0x6c, 0x6d, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61,
	0x73, 0x65, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x63, 0x61, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x66, 0x69, 0x6c,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x63,
	0x61, 0x73, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x6d, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x6d, 0x73, 0x12,
	0x23, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x05, 0x70,
	0x61, 0x67, 0x65, 0x73, 0x1a, 0x2f, 0x0a, 0x13, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xa0, 0x01, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6b, 0x63, 0x61,
	0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x42, 0x4f, 0x4f, 0x4b, 0x43, 0x41,
	0x53, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x42, 0x4f, 0x4f, 0x4b, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x42, 0x4f, 0x4f,
	0x4b, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x41, 0x49, 0x54, 0x10,
	0x02, 0x12, 0x15, 0x0a, 0x11, 0x42, 0x4f, 0x4f, 0x4b, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x42, 0x55, 0x59, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x42, 0x4f, 0x4f, 0x4b,
	0x43, 0x41, 0x53, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x41, 0x4c, 0x45, 0x10, 0x04,
	0x12, 0x16, 0x0a, 0x12, 0x42, 0x4f, 0x4f, 0x4b, 0x43, 0x41, 0x53, 0x45, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x46, 0x52, 0x45, 0x45, 0x10, 0x05, 0x42, 0x0c, 0x5a, 0x0a, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bookcase_proto_rawDescOnce sync.Once
	file_proto_bookcase_proto_rawDescData = file_proto_bookcase_proto_rawDesc
)

func file_proto_bookcase_proto_rawDescGZIP() []byte {
	file_proto_bookcase_proto_rawDescOnce.Do(func() {
		file_proto_bookcase_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bookcase_proto_rawDescData)
	})
	return file_proto_bookcase_proto_rawDescData
}

var file_proto_bookcase_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_bookcase_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_bookcase_proto_goTypes = []interface{}{
	(Bookcase_BookcaseType)(0),               // 0: Bookcase.BookcaseType
	(*Bookcase)(nil),                         // 1: Bookcase
	(*Bookcase_Bookcase)(nil),                // 2: Bookcase.Bookcase
	(*Bookcase_BookcaseBlock)(nil),           // 3: Bookcase.BookcaseBlock
	(*Bookcase_BookcaseBlocksResponse)(nil),  // 4: Bookcase.BookcaseBlocksResponse
	(*Bookcase_BookcaseInfo)(nil),            // 5: Bookcase.BookcaseInfo
	(*Bookcase_Edition)(nil),                 // 6: Bookcase.Edition
	(*Bookcase_EditionBookcaseResponse)(nil), // 7: Bookcase.EditionBookcaseResponse
	(*Bookcase_Work)(nil),                    // 8: Bookcase.Work
	(*Bookcase_WorkBookcaseResponse)(nil),    // 9: Bookcase.WorkBookcaseResponse
	(*Bookcase_Film)(nil),                    // 10: Bookcase.Film
	(*Bookcase_FilmBookcaseResponse)(nil),    // 11: Bookcase.FilmBookcaseResponse
	(*Bookcase_ItemCommentResponse)(nil),     // 12: Bookcase.ItemCommentResponse
	(*Bookcase_Edition_Offers)(nil),          // 13: Bookcase.Edition.Offers
	(*Bookcase_Edition_Offers_Offer)(nil),    // 14: Bookcase.Edition.Offers.Offer
	(*Bookcase_Work_Author)(nil),             // 15: Bookcase.Work.Author
	(*Bookcase_Work_Stats)(nil),              // 16: Bookcase.Work.Stats
	(*Bookcase_Work_Own)(nil),                // 17: Bookcase.Work.Own
	(EditionType)(0),                         // 18: EditionType
	(EditionCorrectnessLevel)(0),             // 19: EditionCorrectnessLevel
	(*Common_Pages)(nil),                     // 20: Common.Pages
	(WorkType)(0),                            // 21: WorkType
	(FilmType)(0),                            // 22: FilmType
}
var file_proto_bookcase_proto_depIdxs = []int32{
	0,  // 0: Bookcase.Bookcase.type:type_name -> Bookcase.BookcaseType
	2,  // 1: Bookcase.BookcaseBlock.bookcases:type_name -> Bookcase.Bookcase
	3,  // 2: Bookcase.BookcaseBlocksResponse.bookcase_blocks:type_name -> Bookcase.BookcaseBlock
	0,  // 3: Bookcase.BookcaseInfo.type:type_name -> Bookcase.BookcaseType
	18, // 4: Bookcase.Edition.type:type_name -> EditionType
	19, // 5: Bookcase.Edition.correctness_level:type_name -> EditionCorrectnessLevel
	13, // 6: Bookcase.Edition.offers:type_name -> Bookcase.Edition.Offers
	5,  // 7: Bookcase.EditionBookcaseResponse.bookcase:type_name -> Bookcase.BookcaseInfo
	6,  // 8: Bookcase.EditionBookcaseResponse.editions:type_name -> Bookcase.Edition
	20, // 9: Bookcase.EditionBookcaseResponse.pages:type_name -> Common.Pages
	21, // 10: Bookcase.Work.type:type_name -> WorkType
	15, // 11: Bookcase.Work.authors:type_name -> Bookcase.Work.Author
	16, // 12: Bookcase.Work.stats:type_name -> Bookcase.Work.Stats
	17, // 13: Bookcase.Work.own:type_name -> Bookcase.Work.Own
	5,  // 14: Bookcase.WorkBookcaseResponse.bookcase:type_name -> Bookcase.BookcaseInfo
	8,  // 15: Bookcase.WorkBookcaseResponse.works:type_name -> Bookcase.Work
	20, // 16: Bookcase.WorkBookcaseResponse.pages:type_name -> Common.Pages
	22, // 17: Bookcase.Film.type:type_name -> FilmType
	5,  // 18: Bookcase.FilmBookcaseResponse.bookcase:type_name -> Bookcase.BookcaseInfo
	10, // 19: Bookcase.FilmBookcaseResponse.films:type_name -> Bookcase.Film
	20, // 20: Bookcase.FilmBookcaseResponse.pages:type_name -> Common.Pages
	14, // 21: Bookcase.Edition.Offers.ozon:type_name -> Bookcase.Edition.Offers.Offer
	14, // 22: Bookcase.Edition.Offers.labirint:type_name -> Bookcase.Edition.Offers.Offer
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_bookcase_proto_init() }
func file_proto_bookcase_proto_init() {
	if File_proto_bookcase_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_edition_proto_init()
	file_proto_work_proto_init()
	file_proto_film_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_bookcase_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_Bookcase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_BookcaseBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_BookcaseBlocksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_BookcaseInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_Edition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_EditionBookcaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_Work); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_WorkBookcaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_Film); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_FilmBookcaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_ItemCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_Edition_Offers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_Edition_Offers_Offer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_Work_Author); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_Work_Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bookcase_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bookcase_Work_Own); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bookcase_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bookcase_proto_goTypes,
		DependencyIndexes: file_proto_bookcase_proto_depIdxs,
		EnumInfos:         file_proto_bookcase_proto_enumTypes,
		MessageInfos:      file_proto_bookcase_proto_msgTypes,
	}.Build()
	File_proto_bookcase_proto = out.File
	file_proto_bookcase_proto_rawDesc = nil
	file_proto_bookcase_proto_goTypes = nil
	file_proto_bookcase_proto_depIdxs = nil
}
