// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1-devel
// 	protoc        v3.11.4
// source: proto/forum.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Forum_Topic_Type int32

const (
	Forum_Topic_UNKNOWN_TYPE Forum_Topic_Type = 0
	// тема
	Forum_Topic_TOPIC Forum_Topic_Type = 1
	// опрос
	Forum_Topic_POLL Forum_Topic_Type = 2
)

// Enum value maps for Forum_Topic_Type.
var (
	Forum_Topic_Type_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "TOPIC",
		2: "POLL",
	}
	Forum_Topic_Type_value = map[string]int32{
		"UNKNOWN_TYPE": 0,
		"TOPIC":        1,
		"POLL":         2,
	}
)

func (x Forum_Topic_Type) Enum() *Forum_Topic_Type {
	p := new(Forum_Topic_Type)
	*p = x
	return p
}

func (x Forum_Topic_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Forum_Topic_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_forum_proto_enumTypes[0].Descriptor()
}

func (Forum_Topic_Type) Type() protoreflect.EnumType {
	return &file_proto_forum_proto_enumTypes[0]
}

func (x Forum_Topic_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Forum_Topic_Type.Descriptor instead.
func (Forum_Topic_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 5, 0}
}

type Forum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Forum) Reset() {
	*x = Forum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum) ProtoMessage() {}

func (x *Forum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum.ProtoReflect.Descriptor instead.
func (*Forum) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0}
}

type Forum_TopicLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id темы
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// название
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Forum_TopicLink) Reset() {
	*x = Forum_TopicLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_TopicLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_TopicLink) ProtoMessage() {}

func (x *Forum_TopicLink) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_TopicLink.ProtoReflect.Descriptor instead.
func (*Forum_TopicLink) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Forum_TopicLink) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Forum_TopicLink) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Forum_TopicMessageDraft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id темы
	TopicId uint64 `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	// данные о создании
	Creation *Common_Creation `protobuf:"bytes,2,opt,name=creation,proto3" json:"creation,omitempty"`
	// текст
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// аттачи
	Attachments []*Common_Attachment `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
}

func (x *Forum_TopicMessageDraft) Reset() {
	*x = Forum_TopicMessageDraft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_TopicMessageDraft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_TopicMessageDraft) ProtoMessage() {}

func (x *Forum_TopicMessageDraft) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_TopicMessageDraft.ProtoReflect.Descriptor instead.
func (*Forum_TopicMessageDraft) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Forum_TopicMessageDraft) GetTopicId() uint64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Forum_TopicMessageDraft) GetCreation() *Common_Creation {
	if x != nil {
		return x.Creation
	}
	return nil
}

func (x *Forum_TopicMessageDraft) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Forum_TopicMessageDraft) GetAttachments() []*Common_Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type Forum_LastMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id сообщения
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// тема, в которую входит сообщение
	Topic *Forum_TopicLink `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// автор
	User *Common_UserLink `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// текст
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// дата и время создания
	Date *timestamp.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *Forum_LastMessage) Reset() {
	*x = Forum_LastMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_LastMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_LastMessage) ProtoMessage() {}

func (x *Forum_LastMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_LastMessage.ProtoReflect.Descriptor instead.
func (*Forum_LastMessage) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Forum_LastMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Forum_LastMessage) GetTopic() *Forum_TopicLink {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Forum_LastMessage) GetUser() *Common_UserLink {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Forum_LastMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Forum_LastMessage) GetDate() *timestamp.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type Forum_TopicMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id сообщения
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// данные о создании
	Creation *Common_Creation `protobuf:"bytes,2,opt,name=creation,proto3" json:"creation,omitempty"`
	// текст
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// текст изъят модератором?
	IsCensored bool `protobuf:"varint,4,opt,name=is_censored,json=isCensored,proto3" json:"is_censored,omitempty"`
	// сообщение не прочитано? (для залогиненных пользователей)
	IsUnread bool `protobuf:"varint,5,opt,name=is_unread,json=isUnread,proto3" json:"is_unread,omitempty"`
	// аттачи
	Attachments []*Common_Attachment `protobuf:"bytes,6,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// статистика
	Stats *Forum_TopicMessage_Stats `protobuf:"bytes,7,opt,name=stats,proto3" json:"stats,omitempty"`
	// права
	Rights *Forum_TopicMessage_Rights `protobuf:"bytes,8,opt,name=rights,proto3" json:"rights,omitempty"`
}

func (x *Forum_TopicMessage) Reset() {
	*x = Forum_TopicMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_TopicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_TopicMessage) ProtoMessage() {}

func (x *Forum_TopicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_TopicMessage.ProtoReflect.Descriptor instead.
func (*Forum_TopicMessage) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Forum_TopicMessage) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Forum_TopicMessage) GetCreation() *Common_Creation {
	if x != nil {
		return x.Creation
	}
	return nil
}

func (x *Forum_TopicMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Forum_TopicMessage) GetIsCensored() bool {
	if x != nil {
		return x.IsCensored
	}
	return false
}

func (x *Forum_TopicMessage) GetIsUnread() bool {
	if x != nil {
		return x.IsUnread
	}
	return false
}

func (x *Forum_TopicMessage) GetAttachments() []*Common_Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *Forum_TopicMessage) GetStats() *Forum_TopicMessage_Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Forum_TopicMessage) GetRights() *Forum_TopicMessage_Rights {
	if x != nil {
		return x.Rights
	}
	return nil
}

type Forum_Poll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// варианты ответов
	AnswerOptions []*Forum_Poll_AnswerOption `protobuf:"bytes,1,rep,name=answer_options,json=answerOptions,proto3" json:"answer_options,omitempty"`
	// проголосовавшие пользователи (если опрос окончен)
	Voters []*Common_UserLink `protobuf:"bytes,2,rep,name=voters,proto3" json:"voters,omitempty"`
}

func (x *Forum_Poll) Reset() {
	*x = Forum_Poll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_Poll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_Poll) ProtoMessage() {}

func (x *Forum_Poll) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_Poll.ProtoReflect.Descriptor instead.
func (*Forum_Poll) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Forum_Poll) GetAnswerOptions() []*Forum_Poll_AnswerOption {
	if x != nil {
		return x.AnswerOptions
	}
	return nil
}

func (x *Forum_Poll) GetVoters() []*Common_UserLink {
	if x != nil {
		return x.Voters
	}
	return nil
}

type Forum_Topic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id темы
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// название
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// тип
	TopicType Forum_Topic_Type `protobuf:"varint,3,opt,name=topic_type,json=topicType,proto3,enum=Forum_Topic_Type" json:"topic_type,omitempty"`
	// данные о создании
	Creation *Common_Creation `protobuf:"bytes,4,opt,name=creation,proto3" json:"creation,omitempty"`
	// тема закрыта?
	IsClosed bool `protobuf:"varint,5,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	// тема закреплена?
	IsPinned bool `protobuf:"varint,6,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	// тема не отмодерирована? (для модераторов и авторов тем)
	IsNotModerated bool `protobuf:"varint,7,opt,name=is_not_moderated,json=isNotModerated,proto3" json:"is_not_moderated,omitempty"`
	// пользователь подписан на тему? (для залогиненных пользователей)
	IsSubscribed bool `protobuf:"varint,8,opt,name=is_subscribed,json=isSubscribed,proto3" json:"is_subscribed,omitempty"`
	// статистика
	Stats *Forum_Topic_Stats `protobuf:"bytes,9,opt,name=stats,proto3" json:"stats,omitempty"`
	// последнее сообщение
	LastMessage *Forum_LastMessage `protobuf:"bytes,10,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	// id первого непрочитанного сообщения (для залогиненных пользователей)
	FirstNotReadMessageId uint64 `protobuf:"varint,11,opt,name=first_not_read_message_id,json=firstNotReadMessageId,proto3" json:"first_not_read_message_id,omitempty"`
}

func (x *Forum_Topic) Reset() {
	*x = Forum_Topic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_Topic) ProtoMessage() {}

func (x *Forum_Topic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_Topic.ProtoReflect.Descriptor instead.
func (*Forum_Topic) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Forum_Topic) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Forum_Topic) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Forum_Topic) GetTopicType() Forum_Topic_Type {
	if x != nil {
		return x.TopicType
	}
	return Forum_Topic_UNKNOWN_TYPE
}

func (x *Forum_Topic) GetCreation() *Common_Creation {
	if x != nil {
		return x.Creation
	}
	return nil
}

func (x *Forum_Topic) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

func (x *Forum_Topic) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

func (x *Forum_Topic) GetIsNotModerated() bool {
	if x != nil {
		return x.IsNotModerated
	}
	return false
}

func (x *Forum_Topic) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

func (x *Forum_Topic) GetStats() *Forum_Topic_Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Forum_Topic) GetLastMessage() *Forum_LastMessage {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *Forum_Topic) GetFirstNotReadMessageId() uint64 {
	if x != nil {
		return x.FirstNotReadMessageId
	}
	return 0
}

type Forum_Forum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id форума
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// название
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// описание
	ForumDescription string `protobuf:"bytes,3,opt,name=forum_description,json=forumDescription,proto3" json:"forum_description,omitempty"`
	// модераторы
	Moderators []*Common_UserLink `protobuf:"bytes,4,rep,name=moderators,proto3" json:"moderators,omitempty"`
	// статистика
	Stats *Forum_Forum_Stats `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	// последнее сообщение
	LastMessage *Forum_LastMessage `protobuf:"bytes,6,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
}

func (x *Forum_Forum) Reset() {
	*x = Forum_Forum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_Forum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_Forum) ProtoMessage() {}

func (x *Forum_Forum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_Forum.ProtoReflect.Descriptor instead.
func (*Forum_Forum) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 6}
}

func (x *Forum_Forum) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Forum_Forum) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Forum_Forum) GetForumDescription() string {
	if x != nil {
		return x.ForumDescription
	}
	return ""
}

func (x *Forum_Forum) GetModerators() []*Common_UserLink {
	if x != nil {
		return x.Moderators
	}
	return nil
}

func (x *Forum_Forum) GetStats() *Forum_Forum_Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Forum_Forum) GetLastMessage() *Forum_LastMessage {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

type Forum_ForumBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id блока форумов
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// название
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// форумы
	Forums []*Forum_Forum `protobuf:"bytes,3,rep,name=forums,proto3" json:"forums,omitempty"`
}

func (x *Forum_ForumBlock) Reset() {
	*x = Forum_ForumBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_ForumBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_ForumBlock) ProtoMessage() {}

func (x *Forum_ForumBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_ForumBlock.ProtoReflect.Descriptor instead.
func (*Forum_ForumBlock) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 7}
}

func (x *Forum_ForumBlock) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Forum_ForumBlock) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Forum_ForumBlock) GetForums() []*Forum_Forum {
	if x != nil {
		return x.Forums
	}
	return nil
}

type Forum_ForumBlocksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// список блоков форумов
	ForumBlocks []*Forum_ForumBlock `protobuf:"bytes,1,rep,name=forum_blocks,json=forumBlocks,proto3" json:"forum_blocks,omitempty"`
}

func (x *Forum_ForumBlocksResponse) Reset() {
	*x = Forum_ForumBlocksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_ForumBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_ForumBlocksResponse) ProtoMessage() {}

func (x *Forum_ForumBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_ForumBlocksResponse.ProtoReflect.Descriptor instead.
func (*Forum_ForumBlocksResponse) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 8}
}

func (x *Forum_ForumBlocksResponse) GetForumBlocks() []*Forum_ForumBlock {
	if x != nil {
		return x.ForumBlocks
	}
	return nil
}

type Forum_ForumTopicsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// модераторы
	Moderators []*Common_UserLink `protobuf:"bytes,1,rep,name=moderators,proto3" json:"moderators,omitempty"`
	// список тем
	Topics []*Forum_Topic `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	// страницы
	Pages *Common_Pages `protobuf:"bytes,3,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *Forum_ForumTopicsResponse) Reset() {
	*x = Forum_ForumTopicsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_ForumTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_ForumTopicsResponse) ProtoMessage() {}

func (x *Forum_ForumTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_ForumTopicsResponse.ProtoReflect.Descriptor instead.
func (*Forum_ForumTopicsResponse) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 9}
}

func (x *Forum_ForumTopicsResponse) GetModerators() []*Common_UserLink {
	if x != nil {
		return x.Moderators
	}
	return nil
}

func (x *Forum_ForumTopicsResponse) GetTopics() []*Forum_Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Forum_ForumTopicsResponse) GetPages() *Common_Pages {
	if x != nil {
		return x.Pages
	}
	return nil
}

type Forum_ForumTopicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// тема
	Topic *Forum_Topic `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// форум, в который входит тема
	Forum *Forum_Forum `protobuf:"bytes,2,opt,name=forum,proto3" json:"forum,omitempty"`
	// опрос (если есть)
	Poll *Forum_Poll `protobuf:"bytes,3,opt,name=poll,proto3" json:"poll,omitempty"`
	// закрепленное сообщение, если есть
	PinnedMessage *Forum_TopicMessage `protobuf:"bytes,4,opt,name=pinned_message,json=pinnedMessage,proto3" json:"pinned_message,omitempty"`
	// сообщения
	Messages []*Forum_TopicMessage `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	// черновик, если есть (для залогиненных пользователей)
	MessageDraft *Forum_TopicMessageDraft `protobuf:"bytes,6,opt,name=message_draft,json=messageDraft,proto3" json:"message_draft,omitempty"`
	// страницы
	Pages *Common_Pages `protobuf:"bytes,7,opt,name=pages,proto3" json:"pages,omitempty"`
}

func (x *Forum_ForumTopicResponse) Reset() {
	*x = Forum_ForumTopicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_ForumTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_ForumTopicResponse) ProtoMessage() {}

func (x *Forum_ForumTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_ForumTopicResponse.ProtoReflect.Descriptor instead.
func (*Forum_ForumTopicResponse) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 10}
}

func (x *Forum_ForumTopicResponse) GetTopic() *Forum_Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *Forum_ForumTopicResponse) GetForum() *Forum_Forum {
	if x != nil {
		return x.Forum
	}
	return nil
}

func (x *Forum_ForumTopicResponse) GetPoll() *Forum_Poll {
	if x != nil {
		return x.Poll
	}
	return nil
}

func (x *Forum_ForumTopicResponse) GetPinnedMessage() *Forum_TopicMessage {
	if x != nil {
		return x.PinnedMessage
	}
	return nil
}

func (x *Forum_ForumTopicResponse) GetMessages() []*Forum_TopicMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Forum_ForumTopicResponse) GetMessageDraft() *Forum_TopicMessageDraft {
	if x != nil {
		return x.MessageDraft
	}
	return nil
}

func (x *Forum_ForumTopicResponse) GetPages() *Common_Pages {
	if x != nil {
		return x.Pages
	}
	return nil
}

type Forum_ForumMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// сообщение
	Message *Forum_TopicMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Forum_ForumMessageResponse) Reset() {
	*x = Forum_ForumMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_ForumMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_ForumMessageResponse) ProtoMessage() {}

func (x *Forum_ForumMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_ForumMessageResponse.ProtoReflect.Descriptor instead.
func (*Forum_ForumMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 11}
}

func (x *Forum_ForumMessageResponse) GetMessage() *Forum_TopicMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type Forum_ForumMessageDraftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// черновик сообщения
	MessageDraft *Forum_TopicMessageDraft `protobuf:"bytes,1,opt,name=message_draft,json=messageDraft,proto3" json:"message_draft,omitempty"`
}

func (x *Forum_ForumMessageDraftResponse) Reset() {
	*x = Forum_ForumMessageDraftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_ForumMessageDraftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_ForumMessageDraftResponse) ProtoMessage() {}

func (x *Forum_ForumMessageDraftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_ForumMessageDraftResponse.ProtoReflect.Descriptor instead.
func (*Forum_ForumMessageDraftResponse) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 12}
}

func (x *Forum_ForumMessageDraftResponse) GetMessageDraft() *Forum_TopicMessageDraft {
	if x != nil {
		return x.MessageDraft
	}
	return nil
}

type Forum_TopicMessage_Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// рейтинг
	Rating int64 `protobuf:"varint,1,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *Forum_TopicMessage_Stats) Reset() {
	*x = Forum_TopicMessage_Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_TopicMessage_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_TopicMessage_Stats) ProtoMessage() {}

func (x *Forum_TopicMessage_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_TopicMessage_Stats.ProtoReflect.Descriptor instead.
func (*Forum_TopicMessage_Stats) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *Forum_TopicMessage_Stats) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type Forum_TopicMessage_Rights struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// на редактирование
	CanEdit bool `protobuf:"varint,1,opt,name=canEdit,proto3" json:"canEdit,omitempty"`
	// на удаление
	CanDelete bool `protobuf:"varint,2,opt,name=canDelete,proto3" json:"canDelete,omitempty"`
	// на выставление "минуса" сообщению
	CanVoteMinus bool `protobuf:"varint,3,opt,name=canVoteMinus,proto3" json:"canVoteMinus,omitempty"`
	// на выставление "плюса" сообщению
	CanVotePlus bool `protobuf:"varint,4,opt,name=canVotePlus,proto3" json:"canVotePlus,omitempty"`
	// на удаление рейтинга (для модераторов)
	CanDeleteVotes bool `protobuf:"varint,5,opt,name=canDeleteVotes,proto3" json:"canDeleteVotes,omitempty"`
}

func (x *Forum_TopicMessage_Rights) Reset() {
	*x = Forum_TopicMessage_Rights{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_TopicMessage_Rights) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_TopicMessage_Rights) ProtoMessage() {}

func (x *Forum_TopicMessage_Rights) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_TopicMessage_Rights.ProtoReflect.Descriptor instead.
func (*Forum_TopicMessage_Rights) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (x *Forum_TopicMessage_Rights) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *Forum_TopicMessage_Rights) GetCanDelete() bool {
	if x != nil {
		return x.CanDelete
	}
	return false
}

func (x *Forum_TopicMessage_Rights) GetCanVoteMinus() bool {
	if x != nil {
		return x.CanVoteMinus
	}
	return false
}

func (x *Forum_TopicMessage_Rights) GetCanVotePlus() bool {
	if x != nil {
		return x.CanVotePlus
	}
	return false
}

func (x *Forum_TopicMessage_Rights) GetCanDeleteVotes() bool {
	if x != nil {
		return x.CanDeleteVotes
	}
	return false
}

type Forum_Poll_AnswerOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// текст
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// количество проголосовавших (если опрос окончен)
	VoterCount uint64 `protobuf:"varint,2,opt,name=voter_count,json=voterCount,proto3" json:"voter_count,omitempty"`
}

func (x *Forum_Poll_AnswerOption) Reset() {
	*x = Forum_Poll_AnswerOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_Poll_AnswerOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_Poll_AnswerOption) ProtoMessage() {}

func (x *Forum_Poll_AnswerOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_Poll_AnswerOption.ProtoReflect.Descriptor instead.
func (*Forum_Poll_AnswerOption) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 4, 0}
}

func (x *Forum_Poll_AnswerOption) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Forum_Poll_AnswerOption) GetVoterCount() uint64 {
	if x != nil {
		return x.VoterCount
	}
	return 0
}

type Forum_Topic_Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// количество сообщений
	MessageCount uint64 `protobuf:"varint,1,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	// количество непрочитанных сообщений (для залогиненных пользователей)
	NotReadMessageCount uint64 `protobuf:"varint,2,opt,name=not_read_message_count,json=notReadMessageCount,proto3" json:"not_read_message_count,omitempty"`
	// количество просмотров
	ViewCount uint64 `protobuf:"varint,3,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
}

func (x *Forum_Topic_Stats) Reset() {
	*x = Forum_Topic_Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_Topic_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_Topic_Stats) ProtoMessage() {}

func (x *Forum_Topic_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_Topic_Stats.ProtoReflect.Descriptor instead.
func (*Forum_Topic_Stats) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 5, 0}
}

func (x *Forum_Topic_Stats) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *Forum_Topic_Stats) GetNotReadMessageCount() uint64 {
	if x != nil {
		return x.NotReadMessageCount
	}
	return 0
}

func (x *Forum_Topic_Stats) GetViewCount() uint64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type Forum_Forum_Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// количество тем
	TopicCount uint64 `protobuf:"varint,1,opt,name=topic_count,json=topicCount,proto3" json:"topic_count,omitempty"`
	// количество неотмодерированных тем (для модераторов)
	NotModeratedTopicCount uint64 `protobuf:"varint,2,opt,name=not_moderated_topic_count,json=notModeratedTopicCount,proto3" json:"not_moderated_topic_count,omitempty"`
	// количество сообщений
	MessageCount uint64 `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	// количество непрочитанных сообщений (для залогиненных пользователей)
	NotReadMessageCount uint64 `protobuf:"varint,4,opt,name=not_read_message_count,json=notReadMessageCount,proto3" json:"not_read_message_count,omitempty"`
}

func (x *Forum_Forum_Stats) Reset() {
	*x = Forum_Forum_Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forum_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forum_Forum_Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forum_Forum_Stats) ProtoMessage() {}

func (x *Forum_Forum_Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forum_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forum_Forum_Stats.ProtoReflect.Descriptor instead.
func (*Forum_Forum_Stats) Descriptor() ([]byte, []int) {
	return file_proto_forum_proto_rawDescGZIP(), []int{0, 6, 0}
}

func (x *Forum_Forum_Stats) GetTopicCount() uint64 {
	if x != nil {
		return x.TopicCount
	}
	return 0
}

func (x *Forum_Forum_Stats) GetNotModeratedTopicCount() uint64 {
	if x != nil {
		return x.NotModeratedTopicCount
	}
	return 0
}

func (x *Forum_Forum_Stats) GetMessageCount() uint64 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *Forum_Forum_Stats) GetNotReadMessageCount() uint64 {
	if x != nil {
		return x.NotReadMessageCount
	}
	return 0
}

var File_proto_forum_proto protoreflect.FileDescriptor

var file_proto_forum_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x17, 0x0a, 0x05, 0x46, 0x6f, 0x72,
	0x75, 0x6d, 0x1a, 0x31, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4c, 0x69, 0x6e, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x1a, 0xa6, 0x01, 0x0a, 0x11, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x72, 0x61, 0x66, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0xaf,
	0x01, 0x0a, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26,
	0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x24, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x1a, 0x8b, 0x04, 0x0a, 0x0c, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x2c, 0x0a, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x63, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x43, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x75, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x55, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x12, 0x34, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x2f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d,
	0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x52, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x1a, 0x1f, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0xae, 0x01,
	0x0a, 0x06, 0x52, 0x69, 0x67, 0x68, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x6e, 0x45,
	0x64, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x61, 0x6e, 0x45, 0x64,
	0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x4d, 0x69, 0x6e, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x63, 0x61, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x4d,
	0x69, 0x6e, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x6e, 0x56, 0x6f, 0x74, 0x65, 0x50,
	0x6c, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x56, 0x6f,
	0x74, 0x65, 0x50, 0x6c, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x61, 0x6e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e,
	0x63, 0x61, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x1a, 0xb6,
	0x01, 0x0a, 0x04, 0x50, 0x6f, 0x6c, 0x6c, 0x12, 0x3f, 0x0a, 0x0e, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x2e, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x76, 0x6f, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x06, 0x76, 0x6f, 0x74, 0x65,
	0x72, 0x73, 0x1a, 0x43, 0x0a, 0x0c, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x6f, 0x74, 0x65, 0x72, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x76, 0x6f, 0x74,
	0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0xe3, 0x04, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x46, 0x6f,
	0x72, 0x75, 0x6d, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x70, 0x69, 0x6e, 0x6e, 0x65,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x50, 0x69, 0x6e, 0x6e, 0x65,
	0x64, 0x12, 0x28, 0x0a, 0x10, 0x69, 0x73, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69, 0x73, 0x4e,
	0x6f, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x69,
	0x73, 0x5f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x64,
	0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x0c, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x38, 0x0a, 0x19, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x72,
	0x65, 0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x15, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x52, 0x65,
	0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x1a, 0x80, 0x01, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x16, 0x6e, 0x6f,
	0x74, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x13, 0x6e, 0x6f, 0x74, 0x52,
	0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x76, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2d,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x4f, 0x50, 0x49,
	0x43, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x4c, 0x4c, 0x10, 0x02, 0x1a, 0xad, 0x03,
	0x0a, 0x05, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2b, 0x0a,
	0x11, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x0a, 0x6d, 0x6f,
	0x64, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x6b,
	0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x46, 0x6f,
	0x72, 0x75, 0x6d, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x46,
	0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0xbd, 0x01,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x19, 0x6e, 0x6f, 0x74, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x16, 0x6e, 0x6f, 0x74,
	0x4d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x16, 0x6e, 0x6f, 0x74, 0x5f,
	0x72, 0x65, 0x61, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x13, 0x6e, 0x6f, 0x74, 0x52, 0x65, 0x61,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0x58, 0x0a,
	0x0a, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x24, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x52,
	0x06, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x73, 0x1a, 0x4b, 0x0a, 0x13, 0x46, 0x6f, 0x72, 0x75, 0x6d,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x0c, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x46, 0x6f, 0x72,
	0x75, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0b, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x1a, 0x92, 0x01, 0x0a, 0x13, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x0a,
	0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x6e, 0x6b, 0x52, 0x0a, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x24,
	0x0a, 0x06, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x06, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x73, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x1a, 0xce, 0x02, 0x0a, 0x12, 0x46, 0x6f,
	0x72, 0x75, 0x6d, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x22, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x46, 0x6f, 0x72, 0x75,
	0x6d, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x75, 0x6d, 0x12, 0x1f, 0x0a, 0x04, 0x70, 0x6f, 0x6c, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x50,
	0x6f, 0x6c, 0x6c, 0x52, 0x04, 0x70, 0x6f, 0x6c, 0x6c, 0x12, 0x3a, 0x0a, 0x0e, 0x70, 0x69, 0x6e,
	0x6e, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x70, 0x69, 0x6e, 0x6e, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x64, 0x72, 0x61, 0x66, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x44, 0x72, 0x61, 0x66, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x45, 0x0a, 0x14, 0x46, 0x6f,
	0x72, 0x75, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x5a, 0x0a, 0x19, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d,
	0x0a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x72, 0x61, 0x66, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x46, 0x6f, 0x72, 0x75, 0x6d, 0x2e, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x72, 0x61, 0x66, 0x74, 0x52,
	0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x72, 0x61, 0x66, 0x74, 0x42, 0x0c, 0x5a,
	0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_forum_proto_rawDescOnce sync.Once
	file_proto_forum_proto_rawDescData = file_proto_forum_proto_rawDesc
)

func file_proto_forum_proto_rawDescGZIP() []byte {
	file_proto_forum_proto_rawDescOnce.Do(func() {
		file_proto_forum_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_forum_proto_rawDescData)
	})
	return file_proto_forum_proto_rawDescData
}

var file_proto_forum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_forum_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_forum_proto_goTypes = []interface{}{
	(Forum_Topic_Type)(0),                   // 0: Forum.Topic.Type
	(*Forum)(nil),                           // 1: Forum
	(*Forum_TopicLink)(nil),                 // 2: Forum.TopicLink
	(*Forum_TopicMessageDraft)(nil),         // 3: Forum.TopicMessageDraft
	(*Forum_LastMessage)(nil),               // 4: Forum.LastMessage
	(*Forum_TopicMessage)(nil),              // 5: Forum.TopicMessage
	(*Forum_Poll)(nil),                      // 6: Forum.Poll
	(*Forum_Topic)(nil),                     // 7: Forum.Topic
	(*Forum_Forum)(nil),                     // 8: Forum.Forum
	(*Forum_ForumBlock)(nil),                // 9: Forum.ForumBlock
	(*Forum_ForumBlocksResponse)(nil),       // 10: Forum.ForumBlocksResponse
	(*Forum_ForumTopicsResponse)(nil),       // 11: Forum.ForumTopicsResponse
	(*Forum_ForumTopicResponse)(nil),        // 12: Forum.ForumTopicResponse
	(*Forum_ForumMessageResponse)(nil),      // 13: Forum.ForumMessageResponse
	(*Forum_ForumMessageDraftResponse)(nil), // 14: Forum.ForumMessageDraftResponse
	(*Forum_TopicMessage_Stats)(nil),        // 15: Forum.TopicMessage.Stats
	(*Forum_TopicMessage_Rights)(nil),       // 16: Forum.TopicMessage.Rights
	(*Forum_Poll_AnswerOption)(nil),         // 17: Forum.Poll.AnswerOption
	(*Forum_Topic_Stats)(nil),               // 18: Forum.Topic.Stats
	(*Forum_Forum_Stats)(nil),               // 19: Forum.Forum.Stats
	(*Common_Creation)(nil),                 // 20: Common.Creation
	(*Common_Attachment)(nil),               // 21: Common.Attachment
	(*Common_UserLink)(nil),                 // 22: Common.UserLink
	(*timestamp.Timestamp)(nil),             // 23: google.protobuf.Timestamp
	(*Common_Pages)(nil),                    // 24: Common.Pages
}
var file_proto_forum_proto_depIdxs = []int32{
	20, // 0: Forum.TopicMessageDraft.creation:type_name -> Common.Creation
	21, // 1: Forum.TopicMessageDraft.attachments:type_name -> Common.Attachment
	2,  // 2: Forum.LastMessage.topic:type_name -> Forum.TopicLink
	22, // 3: Forum.LastMessage.user:type_name -> Common.UserLink
	23, // 4: Forum.LastMessage.date:type_name -> google.protobuf.Timestamp
	20, // 5: Forum.TopicMessage.creation:type_name -> Common.Creation
	21, // 6: Forum.TopicMessage.attachments:type_name -> Common.Attachment
	15, // 7: Forum.TopicMessage.stats:type_name -> Forum.TopicMessage.Stats
	16, // 8: Forum.TopicMessage.rights:type_name -> Forum.TopicMessage.Rights
	17, // 9: Forum.Poll.answer_options:type_name -> Forum.Poll.AnswerOption
	22, // 10: Forum.Poll.voters:type_name -> Common.UserLink
	0,  // 11: Forum.Topic.topic_type:type_name -> Forum.Topic.Type
	20, // 12: Forum.Topic.creation:type_name -> Common.Creation
	18, // 13: Forum.Topic.stats:type_name -> Forum.Topic.Stats
	4,  // 14: Forum.Topic.last_message:type_name -> Forum.LastMessage
	22, // 15: Forum.Forum.moderators:type_name -> Common.UserLink
	19, // 16: Forum.Forum.stats:type_name -> Forum.Forum.Stats
	4,  // 17: Forum.Forum.last_message:type_name -> Forum.LastMessage
	8,  // 18: Forum.ForumBlock.forums:type_name -> Forum.Forum
	9,  // 19: Forum.ForumBlocksResponse.forum_blocks:type_name -> Forum.ForumBlock
	22, // 20: Forum.ForumTopicsResponse.moderators:type_name -> Common.UserLink
	7,  // 21: Forum.ForumTopicsResponse.topics:type_name -> Forum.Topic
	24, // 22: Forum.ForumTopicsResponse.pages:type_name -> Common.Pages
	7,  // 23: Forum.ForumTopicResponse.topic:type_name -> Forum.Topic
	8,  // 24: Forum.ForumTopicResponse.forum:type_name -> Forum.Forum
	6,  // 25: Forum.ForumTopicResponse.poll:type_name -> Forum.Poll
	5,  // 26: Forum.ForumTopicResponse.pinned_message:type_name -> Forum.TopicMessage
	5,  // 27: Forum.ForumTopicResponse.messages:type_name -> Forum.TopicMessage
	3,  // 28: Forum.ForumTopicResponse.message_draft:type_name -> Forum.TopicMessageDraft
	24, // 29: Forum.ForumTopicResponse.pages:type_name -> Common.Pages
	5,  // 30: Forum.ForumMessageResponse.message:type_name -> Forum.TopicMessage
	3,  // 31: Forum.ForumMessageDraftResponse.message_draft:type_name -> Forum.TopicMessageDraft
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_proto_forum_proto_init() }
func file_proto_forum_proto_init() {
	if File_proto_forum_proto != nil {
		return
	}
	file_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_forum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_TopicLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_TopicMessageDraft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_LastMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_TopicMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_Poll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_Topic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_Forum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_ForumBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_ForumBlocksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_ForumTopicsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_ForumTopicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_ForumMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_ForumMessageDraftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_TopicMessage_Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_TopicMessage_Rights); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_Poll_AnswerOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_Topic_Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forum_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forum_Forum_Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_forum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_forum_proto_goTypes,
		DependencyIndexes: file_proto_forum_proto_depIdxs,
		EnumInfos:         file_proto_forum_proto_enumTypes,
		MessageInfos:      file_proto_forum_proto_msgTypes,
	}.Build()
	File_proto_forum_proto = out.File
	file_proto_forum_proto_rawDesc = nil
	file_proto_forum_proto_goTypes = nil
	file_proto_forum_proto_depIdxs = nil
}
