// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blog_models.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Blog struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

type Blog_UserLink struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string   `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=fantlab.Gender" json:"gender,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog_UserLink) Reset()         { *m = Blog_UserLink{} }
func (m *Blog_UserLink) String() string { return proto.CompactTextString(m) }
func (*Blog_UserLink) ProtoMessage()    {}
func (*Blog_UserLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 0}
}

func (m *Blog_UserLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_UserLink.Unmarshal(m, b)
}
func (m *Blog_UserLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_UserLink.Marshal(b, m, deterministic)
}
func (m *Blog_UserLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_UserLink.Merge(m, src)
}
func (m *Blog_UserLink) XXX_Size() int {
	return xxx_messageInfo_Blog_UserLink.Size(m)
}
func (m *Blog_UserLink) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_UserLink.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_UserLink proto.InternalMessageInfo

func (m *Blog_UserLink) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Blog_UserLink) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Blog_UserLink) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Blog_UserLink) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

func (m *Blog_UserLink) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type Blog_Creation struct {
	User                 *Blog_UserLink       `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Blog_Creation) Reset()         { *m = Blog_Creation{} }
func (m *Blog_Creation) String() string { return proto.CompactTextString(m) }
func (*Blog_Creation) ProtoMessage()    {}
func (*Blog_Creation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 1}
}

func (m *Blog_Creation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_Creation.Unmarshal(m, b)
}
func (m *Blog_Creation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_Creation.Marshal(b, m, deterministic)
}
func (m *Blog_Creation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_Creation.Merge(m, src)
}
func (m *Blog_Creation) XXX_Size() int {
	return xxx_messageInfo_Blog_Creation.Size(m)
}
func (m *Blog_Creation) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_Creation.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_Creation proto.InternalMessageInfo

func (m *Blog_Creation) GetUser() *Blog_UserLink {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Blog_Creation) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type Blog_LastArticle struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	User                 *Blog_UserLink       `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Blog_LastArticle) Reset()         { *m = Blog_LastArticle{} }
func (m *Blog_LastArticle) String() string { return proto.CompactTextString(m) }
func (*Blog_LastArticle) ProtoMessage()    {}
func (*Blog_LastArticle) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 2}
}

func (m *Blog_LastArticle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_LastArticle.Unmarshal(m, b)
}
func (m *Blog_LastArticle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_LastArticle.Marshal(b, m, deterministic)
}
func (m *Blog_LastArticle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_LastArticle.Merge(m, src)
}
func (m *Blog_LastArticle) XXX_Size() int {
	return xxx_messageInfo_Blog_LastArticle.Size(m)
}
func (m *Blog_LastArticle) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_LastArticle.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_LastArticle proto.InternalMessageInfo

func (m *Blog_LastArticle) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Blog_LastArticle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog_LastArticle) GetUser() *Blog_UserLink {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Blog_LastArticle) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type Blog_Community struct {
	Id                   uint32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CommunityDescription string                `protobuf:"bytes,3,opt,name=community_description,json=communityDescription,proto3" json:"community_description,omitempty"`
	Stats                *Blog_Community_Stats `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	LastArticle          *Blog_LastArticle     `protobuf:"bytes,5,opt,name=last_article,json=lastArticle,proto3" json:"last_article,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Blog_Community) Reset()         { *m = Blog_Community{} }
func (m *Blog_Community) String() string { return proto.CompactTextString(m) }
func (*Blog_Community) ProtoMessage()    {}
func (*Blog_Community) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 3}
}

func (m *Blog_Community) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_Community.Unmarshal(m, b)
}
func (m *Blog_Community) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_Community.Marshal(b, m, deterministic)
}
func (m *Blog_Community) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_Community.Merge(m, src)
}
func (m *Blog_Community) XXX_Size() int {
	return xxx_messageInfo_Blog_Community.Size(m)
}
func (m *Blog_Community) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_Community.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_Community proto.InternalMessageInfo

func (m *Blog_Community) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Blog_Community) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog_Community) GetCommunityDescription() string {
	if m != nil {
		return m.CommunityDescription
	}
	return ""
}

func (m *Blog_Community) GetStats() *Blog_Community_Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Blog_Community) GetLastArticle() *Blog_LastArticle {
	if m != nil {
		return m.LastArticle
	}
	return nil
}

type Blog_Community_Stats struct {
	ArticleCount         uint32   `protobuf:"varint,1,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	SubscriberCount      uint32   `protobuf:"varint,2,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog_Community_Stats) Reset()         { *m = Blog_Community_Stats{} }
func (m *Blog_Community_Stats) String() string { return proto.CompactTextString(m) }
func (*Blog_Community_Stats) ProtoMessage()    {}
func (*Blog_Community_Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 3, 0}
}

func (m *Blog_Community_Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_Community_Stats.Unmarshal(m, b)
}
func (m *Blog_Community_Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_Community_Stats.Marshal(b, m, deterministic)
}
func (m *Blog_Community_Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_Community_Stats.Merge(m, src)
}
func (m *Blog_Community_Stats) XXX_Size() int {
	return xxx_messageInfo_Blog_Community_Stats.Size(m)
}
func (m *Blog_Community_Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_Community_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_Community_Stats proto.InternalMessageInfo

func (m *Blog_Community_Stats) GetArticleCount() uint32 {
	if m != nil {
		return m.ArticleCount
	}
	return 0
}

func (m *Blog_Community_Stats) GetSubscriberCount() uint32 {
	if m != nil {
		return m.SubscriberCount
	}
	return 0
}

type Blog_Article struct {
	Id                   uint32              `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string              `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Creation             *Blog_Creation      `protobuf:"bytes,3,opt,name=creation,proto3" json:"creation,omitempty"`
	Text                 string              `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Tags                 string              `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	Stats                *Blog_Article_Stats `protobuf:"bytes,6,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Blog_Article) Reset()         { *m = Blog_Article{} }
func (m *Blog_Article) String() string { return proto.CompactTextString(m) }
func (*Blog_Article) ProtoMessage()    {}
func (*Blog_Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 4}
}

func (m *Blog_Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_Article.Unmarshal(m, b)
}
func (m *Blog_Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_Article.Marshal(b, m, deterministic)
}
func (m *Blog_Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_Article.Merge(m, src)
}
func (m *Blog_Article) XXX_Size() int {
	return xxx_messageInfo_Blog_Article.Size(m)
}
func (m *Blog_Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_Article proto.InternalMessageInfo

func (m *Blog_Article) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Blog_Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog_Article) GetCreation() *Blog_Creation {
	if m != nil {
		return m.Creation
	}
	return nil
}

func (m *Blog_Article) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Blog_Article) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *Blog_Article) GetStats() *Blog_Article_Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type Blog_Article_Stats struct {
	LikeCount            uint32   `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ViewCount            uint32   `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	CommentCount         uint32   `protobuf:"varint,3,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog_Article_Stats) Reset()         { *m = Blog_Article_Stats{} }
func (m *Blog_Article_Stats) String() string { return proto.CompactTextString(m) }
func (*Blog_Article_Stats) ProtoMessage()    {}
func (*Blog_Article_Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 4, 0}
}

func (m *Blog_Article_Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_Article_Stats.Unmarshal(m, b)
}
func (m *Blog_Article_Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_Article_Stats.Marshal(b, m, deterministic)
}
func (m *Blog_Article_Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_Article_Stats.Merge(m, src)
}
func (m *Blog_Article_Stats) XXX_Size() int {
	return xxx_messageInfo_Blog_Article_Stats.Size(m)
}
func (m *Blog_Article_Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_Article_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_Article_Stats proto.InternalMessageInfo

func (m *Blog_Article_Stats) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *Blog_Article_Stats) GetViewCount() uint32 {
	if m != nil {
		return m.ViewCount
	}
	return 0
}

func (m *Blog_Article_Stats) GetCommentCount() uint32 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

type Blog_Blog struct {
	Id                   uint32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User                 *Blog_UserLink    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	IsClosed             bool              `protobuf:"varint,3,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	Stats                *Blog_Blog_Stats  `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	LastArticle          *Blog_LastArticle `protobuf:"bytes,5,opt,name=last_article,json=lastArticle,proto3" json:"last_article,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Blog_Blog) Reset()         { *m = Blog_Blog{} }
func (m *Blog_Blog) String() string { return proto.CompactTextString(m) }
func (*Blog_Blog) ProtoMessage()    {}
func (*Blog_Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 5}
}

func (m *Blog_Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_Blog.Unmarshal(m, b)
}
func (m *Blog_Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_Blog.Marshal(b, m, deterministic)
}
func (m *Blog_Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_Blog.Merge(m, src)
}
func (m *Blog_Blog) XXX_Size() int {
	return xxx_messageInfo_Blog_Blog.Size(m)
}
func (m *Blog_Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_Blog proto.InternalMessageInfo

func (m *Blog_Blog) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Blog_Blog) GetUser() *Blog_UserLink {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Blog_Blog) GetIsClosed() bool {
	if m != nil {
		return m.IsClosed
	}
	return false
}

func (m *Blog_Blog) GetStats() *Blog_Blog_Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Blog_Blog) GetLastArticle() *Blog_LastArticle {
	if m != nil {
		return m.LastArticle
	}
	return nil
}

type Blog_Blog_Stats struct {
	ArticleCount         uint32   `protobuf:"varint,1,opt,name=article_count,json=articleCount,proto3" json:"article_count,omitempty"`
	SubscriberCount      uint32   `protobuf:"varint,2,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blog_Blog_Stats) Reset()         { *m = Blog_Blog_Stats{} }
func (m *Blog_Blog_Stats) String() string { return proto.CompactTextString(m) }
func (*Blog_Blog_Stats) ProtoMessage()    {}
func (*Blog_Blog_Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 5, 0}
}

func (m *Blog_Blog_Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_Blog_Stats.Unmarshal(m, b)
}
func (m *Blog_Blog_Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_Blog_Stats.Marshal(b, m, deterministic)
}
func (m *Blog_Blog_Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_Blog_Stats.Merge(m, src)
}
func (m *Blog_Blog_Stats) XXX_Size() int {
	return xxx_messageInfo_Blog_Blog_Stats.Size(m)
}
func (m *Blog_Blog_Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_Blog_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_Blog_Stats proto.InternalMessageInfo

func (m *Blog_Blog_Stats) GetArticleCount() uint32 {
	if m != nil {
		return m.ArticleCount
	}
	return 0
}

func (m *Blog_Blog_Stats) GetSubscriberCount() uint32 {
	if m != nil {
		return m.SubscriberCount
	}
	return 0
}

type Blog_CommunitiesResponse struct {
	Main                 []*Blog_Community `protobuf:"bytes,1,rep,name=main,proto3" json:"main,omitempty"`
	Additional           []*Blog_Community `protobuf:"bytes,2,rep,name=additional,proto3" json:"additional,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Blog_CommunitiesResponse) Reset()         { *m = Blog_CommunitiesResponse{} }
func (m *Blog_CommunitiesResponse) String() string { return proto.CompactTextString(m) }
func (*Blog_CommunitiesResponse) ProtoMessage()    {}
func (*Blog_CommunitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 6}
}

func (m *Blog_CommunitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_CommunitiesResponse.Unmarshal(m, b)
}
func (m *Blog_CommunitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_CommunitiesResponse.Marshal(b, m, deterministic)
}
func (m *Blog_CommunitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_CommunitiesResponse.Merge(m, src)
}
func (m *Blog_CommunitiesResponse) XXX_Size() int {
	return xxx_messageInfo_Blog_CommunitiesResponse.Size(m)
}
func (m *Blog_CommunitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_CommunitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_CommunitiesResponse proto.InternalMessageInfo

func (m *Blog_CommunitiesResponse) GetMain() []*Blog_Community {
	if m != nil {
		return m.Main
	}
	return nil
}

func (m *Blog_CommunitiesResponse) GetAdditional() []*Blog_Community {
	if m != nil {
		return m.Additional
	}
	return nil
}

type Blog_BlogsResponse struct {
	Blogs                []*Blog_Blog `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Blog_BlogsResponse) Reset()         { *m = Blog_BlogsResponse{} }
func (m *Blog_BlogsResponse) String() string { return proto.CompactTextString(m) }
func (*Blog_BlogsResponse) ProtoMessage()    {}
func (*Blog_BlogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 7}
}

func (m *Blog_BlogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_BlogsResponse.Unmarshal(m, b)
}
func (m *Blog_BlogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_BlogsResponse.Marshal(b, m, deterministic)
}
func (m *Blog_BlogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_BlogsResponse.Merge(m, src)
}
func (m *Blog_BlogsResponse) XXX_Size() int {
	return xxx_messageInfo_Blog_BlogsResponse.Size(m)
}
func (m *Blog_BlogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_BlogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_BlogsResponse proto.InternalMessageInfo

func (m *Blog_BlogsResponse) GetBlogs() []*Blog_Blog {
	if m != nil {
		return m.Blogs
	}
	return nil
}

type Blog_ArticlesResponse struct {
	Articles             []*Blog_Article `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Blog_ArticlesResponse) Reset()         { *m = Blog_ArticlesResponse{} }
func (m *Blog_ArticlesResponse) String() string { return proto.CompactTextString(m) }
func (*Blog_ArticlesResponse) ProtoMessage()    {}
func (*Blog_ArticlesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3db3de3fa4b90ae2, []int{0, 8}
}

func (m *Blog_ArticlesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog_ArticlesResponse.Unmarshal(m, b)
}
func (m *Blog_ArticlesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog_ArticlesResponse.Marshal(b, m, deterministic)
}
func (m *Blog_ArticlesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog_ArticlesResponse.Merge(m, src)
}
func (m *Blog_ArticlesResponse) XXX_Size() int {
	return xxx_messageInfo_Blog_ArticlesResponse.Size(m)
}
func (m *Blog_ArticlesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog_ArticlesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Blog_ArticlesResponse proto.InternalMessageInfo

func (m *Blog_ArticlesResponse) GetArticles() []*Blog_Article {
	if m != nil {
		return m.Articles
	}
	return nil
}

func init() {
	proto.RegisterType((*Blog)(nil), "fantlab.blog.Blog")
	proto.RegisterType((*Blog_UserLink)(nil), "fantlab.blog.Blog.UserLink")
	proto.RegisterType((*Blog_Creation)(nil), "fantlab.blog.Blog.Creation")
	proto.RegisterType((*Blog_LastArticle)(nil), "fantlab.blog.Blog.LastArticle")
	proto.RegisterType((*Blog_Community)(nil), "fantlab.blog.Blog.Community")
	proto.RegisterType((*Blog_Community_Stats)(nil), "fantlab.blog.Blog.Community.Stats")
	proto.RegisterType((*Blog_Article)(nil), "fantlab.blog.Blog.Article")
	proto.RegisterType((*Blog_Article_Stats)(nil), "fantlab.blog.Blog.Article.Stats")
	proto.RegisterType((*Blog_Blog)(nil), "fantlab.blog.Blog.Blog")
	proto.RegisterType((*Blog_Blog_Stats)(nil), "fantlab.blog.Blog.Blog.Stats")
	proto.RegisterType((*Blog_CommunitiesResponse)(nil), "fantlab.blog.Blog.CommunitiesResponse")
	proto.RegisterType((*Blog_BlogsResponse)(nil), "fantlab.blog.Blog.BlogsResponse")
	proto.RegisterType((*Blog_ArticlesResponse)(nil), "fantlab.blog.Blog.ArticlesResponse")
}

func init() { proto.RegisterFile("proto/blog_models.proto", fileDescriptor_3db3de3fa4b90ae2) }

var fileDescriptor_3db3de3fa4b90ae2 = []byte{
	// 659 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0xd2, 0xb4, 0xa4, 0xb7, 0xed, 0x36, 0x99, 0xc1, 0x42, 0xc6, 0xa0, 0xda, 0x1e, 0x28,
	0x0f, 0xa4, 0xa8, 0x93, 0x06, 0x0f, 0x08, 0x69, 0x2b, 0x12, 0x12, 0xda, 0x93, 0x01, 0x21, 0xf1,
	0x52, 0x39, 0x89, 0x57, 0x99, 0x25, 0x71, 0x14, 0xbb, 0x03, 0x3e, 0x60, 0x7f, 0xc0, 0xa7, 0xc0,
	0x1b, 0x9f, 0xc1, 0x07, 0x21, 0x3b, 0x76, 0xbb, 0x8a, 0x6e, 0xea, 0x1e, 0x79, 0xa9, 0x7c, 0xcf,
	0x3d, 0xbe, 0x3d, 0xf7, 0xdc, 0xeb, 0xc0, 0x4e, 0x59, 0x71, 0xc9, 0x87, 0x71, 0xc6, 0xa7, 0x93,
	0x9c, 0xa7, 0x34, 0x13, 0x91, 0x46, 0x50, 0xf7, 0x8c, 0x14, 0x32, 0x23, 0x71, 0xa4, 0x52, 0xe1,
	0x83, 0x9a, 0x96, 0xf0, 0x3c, 0xe7, 0xc5, 0x12, 0x31, 0x7c, 0x3c, 0xe5, 0x7c, 0x9a, 0xd1, 0xa1,
	0x8e, 0xe2, 0xd9, 0xd9, 0x50, 0xb2, 0x9c, 0x0a, 0x49, 0xf2, 0xb2, 0x26, 0xec, 0xff, 0xe9, 0x82,
	0x77, 0xa2, 0x8a, 0x5c, 0x3a, 0xe0, 0x7f, 0x14, 0xb4, 0x3a, 0x65, 0xc5, 0x39, 0xda, 0x00, 0x97,
	0xa5, 0x81, 0xd3, 0x77, 0x06, 0x3d, 0xec, 0xb2, 0x14, 0x6d, 0x43, 0x33, 0xe3, 0x53, 0x56, 0x04,
	0x6e, 0xdf, 0x19, 0xb4, 0x71, 0x1d, 0x20, 0x04, 0x5e, 0x41, 0x72, 0x1a, 0x34, 0x34, 0xa8, 0xcf,
	0xe8, 0x09, 0xb4, 0xa6, 0xb4, 0x48, 0x69, 0x15, 0x78, 0x7d, 0x67, 0xb0, 0x31, 0xda, 0x8c, 0xac,
	0xd4, 0xb7, 0x1a, 0xc6, 0x26, 0x8d, 0xee, 0x43, 0x8b, 0x5c, 0x10, 0x49, 0xaa, 0xa0, 0xa9, 0xaf,
	0x9b, 0x28, 0x3c, 0x07, 0x7f, 0x5c, 0x51, 0x22, 0x19, 0x2f, 0xd0, 0x10, 0xbc, 0x99, 0xa0, 0x95,
	0x16, 0xd2, 0x19, 0xed, 0x46, 0x57, 0xbb, 0x8e, 0x94, 0xea, 0xc8, 0x2a, 0xc6, 0x9a, 0x88, 0x22,
	0xf0, 0x52, 0x22, 0xa9, 0x96, 0xd9, 0x19, 0x85, 0x51, 0xdd, 0x7d, 0x64, 0xbb, 0x8f, 0x3e, 0xd8,
	0xee, 0xb1, 0xe6, 0x85, 0x3f, 0x1c, 0xe8, 0x9c, 0x12, 0x21, 0x8f, 0x2b, 0xc9, 0x92, 0x8c, 0xae,
	0xea, 0x5b, 0x32, 0x99, 0x51, 0xdb, 0xb7, 0x0e, 0xe6, 0xb2, 0x1a, 0xb7, 0x95, 0xe5, 0xad, 0x29,
	0xeb, 0xb7, 0x0b, 0xed, 0x31, 0xcf, 0xf3, 0x59, 0xc1, 0xe4, 0xf7, 0x35, 0x45, 0x1d, 0xc2, 0xbd,
	0xc4, 0x5e, 0x99, 0xa4, 0x54, 0x24, 0x15, 0x2b, 0x95, 0x89, 0x66, 0x3a, 0xdb, 0xf3, 0xe4, 0x9b,
	0x45, 0x0e, 0xbd, 0x84, 0xa6, 0x90, 0x44, 0x0a, 0xa3, 0x6c, 0x7f, 0x45, 0x2b, 0x73, 0x1d, 0xd1,
	0x7b, 0xc5, 0xc4, 0xf5, 0x05, 0x74, 0x0c, 0xdd, 0x8c, 0x08, 0x39, 0x21, 0xb5, 0x73, 0x7a, 0x88,
	0x9d, 0xd1, 0xa3, 0x15, 0x05, 0xae, 0xf8, 0x8b, 0x3b, 0xd9, 0x22, 0x08, 0x3f, 0x41, 0x53, 0x97,
	0x44, 0x07, 0xd0, 0x33, 0x65, 0x26, 0x09, 0x9f, 0x15, 0xd2, 0xf4, 0xda, 0x35, 0xe0, 0x58, 0x61,
	0xe8, 0x29, 0x6c, 0x89, 0x59, 0xac, 0xa4, 0xc7, 0xb4, 0x32, 0x3c, 0x57, 0xf3, 0x36, 0x17, 0xb8,
	0xa6, 0x86, 0x3f, 0x5d, 0xb8, 0x73, 0xbb, 0x89, 0xbe, 0x00, 0x3f, 0x31, 0x4b, 0x77, 0xc3, 0x54,
	0xed, 0x5e, 0xe2, 0x39, 0x59, 0x3d, 0x01, 0x49, 0xbf, 0x49, 0xed, 0x5f, 0x1b, 0xeb, 0xb3, 0xc6,
	0xc8, 0x54, 0x98, 0xbd, 0xd6, 0x67, 0x74, 0x64, 0x8d, 0x6e, 0xe9, 0xea, 0xfd, 0x15, 0xd5, 0x8d,
	0xe2, 0x25, 0x9b, 0xc3, 0x2f, 0xd6, 0xa3, 0x3d, 0x80, 0x8c, 0x9d, 0x2f, 0x1b, 0xd4, 0x56, 0x48,
	0xed, 0xce, 0x1e, 0xc0, 0x05, 0xa3, 0x5f, 0x97, 0x7c, 0x69, 0x2b, 0xa4, 0x4e, 0x1f, 0x40, 0x4f,
	0xcd, 0x9f, 0x16, 0xd2, 0x30, 0x1a, 0xb5, 0xc3, 0x06, 0xac, 0x6d, 0xfb, 0xe5, 0xd6, 0x9f, 0x82,
	0x7f, 0x3c, 0xb3, 0xfb, 0xee, 0xae, 0xbb, 0xef, 0xbb, 0xd0, 0x66, 0x62, 0x92, 0x64, 0x5c, 0xd0,
	0x54, 0xff, 0x95, 0x8f, 0x7d, 0x26, 0xc6, 0x3a, 0x46, 0x87, 0xcb, 0x3b, 0xb7, 0xb7, 0xa2, 0x9c,
	0xfe, 0xf9, 0x6f, 0xd6, 0xed, 0xd2, 0x81, 0xbb, 0xf6, 0x95, 0x30, 0x2a, 0x30, 0x15, 0x25, 0x2f,
	0x04, 0x45, 0xcf, 0xc1, 0xcb, 0x09, 0x2b, 0x02, 0xa7, 0xdf, 0x18, 0x74, 0x46, 0x0f, 0x6f, 0x7a,
	0x5b, 0x58, 0x33, 0xd1, 0x2b, 0x00, 0x92, 0xa6, 0x4c, 0x6d, 0x16, 0xc9, 0x02, 0x77, 0x8d, 0x7b,
	0x57, 0xf8, 0xe1, 0x6b, 0xe8, 0xa9, 0xec, 0x42, 0xc0, 0x33, 0x68, 0xaa, 0x3b, 0xc2, 0x28, 0xd8,
	0xb9, 0xc6, 0x69, 0x5c, 0xb3, 0xc2, 0x77, 0xb0, 0x65, 0xbc, 0x5a, 0x94, 0x38, 0x02, 0xdf, 0xd8,
	0x62, 0xab, 0x84, 0xd7, 0xaf, 0x2e, 0x9e, 0x73, 0x4f, 0xfc, 0xcf, 0x2d, 0x52, 0x96, 0xc3, 0x32,
	0x8e, 0x5b, 0xfa, 0x2b, 0x77, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0x42, 0x83, 0x94, 0x73, 0xcc,
	0x06, 0x00, 0x00,
}
