// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Common_Gender int32

const (
	Common_UNKNOWN Common_Gender = 0
	Common_MALE    Common_Gender = 1
	Common_FEMALE  Common_Gender = 2
)

var Common_Gender_name = map[int32]string{
	0: "UNKNOWN",
	1: "MALE",
	2: "FEMALE",
}

var Common_Gender_value = map[string]int32{
	"UNKNOWN": 0,
	"MALE":    1,
	"FEMALE":  2,
}

func (x Common_Gender) String() string {
	return proto.EnumName(Common_Gender_name, int32(x))
}

func (Common_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{0, 0}
}

type Common struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Common) Reset()         { *m = Common{} }
func (m *Common) String() string { return proto.CompactTextString(m) }
func (*Common) ProtoMessage()    {}
func (*Common) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{0}
}

func (m *Common) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common.Unmarshal(m, b)
}
func (m *Common) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common.Marshal(b, m, deterministic)
}
func (m *Common) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common.Merge(m, src)
}
func (m *Common) XXX_Size() int {
	return xxx_messageInfo_Common.Size(m)
}
func (m *Common) XXX_DiscardUnknown() {
	xxx_messageInfo_Common.DiscardUnknown(m)
}

var xxx_messageInfo_Common proto.InternalMessageInfo

type Common_UserLink struct {
	Id                   uint32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login                string        `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Gender               Common_Gender `protobuf:"varint,4,opt,name=gender,proto3,enum=fantlab.Common_Gender" json:"gender,omitempty"`
	Avatar               string        `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Class                uint32        `protobuf:"varint,6,opt,name=class,proto3" json:"class,omitempty"`
	Sign                 string        `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Common_UserLink) Reset()         { *m = Common_UserLink{} }
func (m *Common_UserLink) String() string { return proto.CompactTextString(m) }
func (*Common_UserLink) ProtoMessage()    {}
func (*Common_UserLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{0, 0}
}

func (m *Common_UserLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common_UserLink.Unmarshal(m, b)
}
func (m *Common_UserLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common_UserLink.Marshal(b, m, deterministic)
}
func (m *Common_UserLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common_UserLink.Merge(m, src)
}
func (m *Common_UserLink) XXX_Size() int {
	return xxx_messageInfo_Common_UserLink.Size(m)
}
func (m *Common_UserLink) XXX_DiscardUnknown() {
	xxx_messageInfo_Common_UserLink.DiscardUnknown(m)
}

var xxx_messageInfo_Common_UserLink proto.InternalMessageInfo

func (m *Common_UserLink) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Common_UserLink) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *Common_UserLink) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Common_UserLink) GetGender() Common_Gender {
	if m != nil {
		return m.Gender
	}
	return Common_UNKNOWN
}

func (m *Common_UserLink) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Common_UserLink) GetClass() uint32 {
	if m != nil {
		return m.Class
	}
	return 0
}

func (m *Common_UserLink) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

type Common_Creation struct {
	User                 *Common_UserLink     `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Common_Creation) Reset()         { *m = Common_Creation{} }
func (m *Common_Creation) String() string { return proto.CompactTextString(m) }
func (*Common_Creation) ProtoMessage()    {}
func (*Common_Creation) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{0, 1}
}

func (m *Common_Creation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Common_Creation.Unmarshal(m, b)
}
func (m *Common_Creation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Common_Creation.Marshal(b, m, deterministic)
}
func (m *Common_Creation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Common_Creation.Merge(m, src)
}
func (m *Common_Creation) XXX_Size() int {
	return xxx_messageInfo_Common_Creation.Size(m)
}
func (m *Common_Creation) XXX_DiscardUnknown() {
	xxx_messageInfo_Common_Creation.DiscardUnknown(m)
}

var xxx_messageInfo_Common_Creation proto.InternalMessageInfo

func (m *Common_Creation) GetUser() *Common_UserLink {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Common_Creation) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func init() {
	proto.RegisterEnum("fantlab.Common_Gender", Common_Gender_name, Common_Gender_value)
	proto.RegisterType((*Common)(nil), "fantlab.Common")
	proto.RegisterType((*Common_UserLink)(nil), "fantlab.Common.UserLink")
	proto.RegisterType((*Common_Creation)(nil), "fantlab.Common.Creation")
}

func init() { proto.RegisterFile("proto/common.proto", fileDescriptor_1747d3070a2311a0) }

var fileDescriptor_1747d3070a2311a0 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0xb5, 0xb5, 0xcb, 0xea, 0x1d, 0x8e, 0x71, 0x91, 0x11, 0xfa, 0xe2, 0xd8, 0xd3, 0x40, 0x49,
	0x61, 0x7e, 0x81, 0x8e, 0xe9, 0x83, 0x73, 0x42, 0x71, 0x08, 0xbe, 0xa5, 0x6b, 0x56, 0x83, 0x6d,
	0x52, 0xda, 0xcc, 0x4f, 0xf3, 0x5b, 0xfc, 0x1c, 0xd9, 0xcd, 0xf6, 0xe2, 0xdb, 0x39, 0x37, 0x27,
	0xf7, 0x9c, 0x7b, 0x00, 0x9b, 0xd6, 0x3a, 0x9b, 0x6e, 0x6d, 0x5d, 0x5b, 0x23, 0x88, 0x60, 0x7f,
	0x27, 0x8d, 0xab, 0x64, 0x9e, 0x5c, 0x97, 0xd6, 0x96, 0x95, 0x4a, 0x69, 0x9c, 0xef, 0x77, 0xa9,
	0xd3, 0xb5, 0xea, 0x9c, 0xac, 0x1b, 0xaf, 0x9c, 0xfe, 0x86, 0xc0, 0x16, 0xf4, 0x35, 0xf9, 0x09,
	0x20, 0xde, 0x74, 0xaa, 0x5d, 0x69, 0xf3, 0x85, 0x43, 0x08, 0x75, 0xc1, 0x83, 0x49, 0x30, 0xbb,
	0xcc, 0x42, 0x5d, 0xe0, 0x15, 0xf4, 0x2a, 0x5b, 0x6a, 0xc3, 0xc3, 0x49, 0x30, 0xbb, 0xc8, 0x3c,
	0x41, 0x84, 0xc8, 0xc8, 0x5a, 0xf1, 0x73, 0x1a, 0x12, 0x46, 0x01, 0xac, 0x54, 0xa6, 0x50, 0x2d,
	0x8f, 0x26, 0xc1, 0x6c, 0x38, 0x1f, 0x8b, 0x63, 0x18, 0xe1, 0x7d, 0xc4, 0x13, 0xbd, 0x66, 0x47,
	0x15, 0x8e, 0x81, 0xc9, 0x6f, 0xe9, 0x64, 0xcb, 0x7b, 0xb4, 0xe5, 0xc8, 0x0e, 0x8e, 0xdb, 0x4a,
	0x76, 0x1d, 0x67, 0x14, 0xc2, 0x93, 0x83, 0x63, 0xa7, 0x4b, 0xc3, 0xfb, 0xde, 0xf1, 0x80, 0x93,
	0x4f, 0x88, 0x17, 0xad, 0x92, 0x4e, 0x5b, 0x83, 0xb7, 0x10, 0xed, 0x3b, 0xd5, 0x52, 0xf2, 0xc1,
	0x9c, 0xff, 0xf7, 0x3e, 0xdd, 0x97, 0x91, 0x0a, 0x05, 0x44, 0x85, 0x74, 0x8a, 0x8e, 0x1a, 0xcc,
	0x13, 0xe1, 0xdb, 0x12, 0xa7, 0xb6, 0xc4, 0xdb, 0xa9, 0xad, 0x8c, 0x74, 0xd3, 0x1b, 0x60, 0x3e,
	0x3d, 0x0e, 0xa0, 0xbf, 0x59, 0x3f, 0xaf, 0x5f, 0xdf, 0xd7, 0xa3, 0x33, 0x8c, 0x21, 0x7a, 0xb9,
	0x5f, 0x2d, 0x47, 0x01, 0x02, 0xb0, 0xc7, 0x25, 0xe1, 0xf0, 0x21, 0xfe, 0x60, 0xb2, 0x69, 0xd2,
	0x26, 0xcf, 0x19, 0x2d, 0xbc, 0xfb, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xed, 0xcd, 0xed, 0xb5, 0xab,
	0x01, 0x00, 0x00,
}
