// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/errors.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error_Status int32

const (
	Error_UNKNOWN_STATUS       Error_Status = 0
	Error_SOMETHING_WENT_WRONG Error_Status = 1
	Error_INVALID_PARAMETER    Error_Status = 2
	Error_NOT_FOUND            Error_Status = 3
	Error_INVALID_PASSWORD     Error_Status = 4
	Error_LOG_OUT_FIRST        Error_Status = 5
)

var Error_Status_name = map[int32]string{
	0: "UNKNOWN_STATUS",
	1: "SOMETHING_WENT_WRONG",
	2: "INVALID_PARAMETER",
	3: "NOT_FOUND",
	4: "INVALID_PASSWORD",
	5: "LOG_OUT_FIRST",
}

var Error_Status_value = map[string]int32{
	"UNKNOWN_STATUS":       0,
	"SOMETHING_WENT_WRONG": 1,
	"INVALID_PARAMETER":    2,
	"NOT_FOUND":            3,
	"INVALID_PASSWORD":     4,
	"LOG_OUT_FIRST":        5,
}

func (x Error_Status) String() string {
	return proto.EnumName(Error_Status_name, int32(x))
}

func (Error_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_176b67d994589ed1, []int{0, 0}
}

type Error struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_176b67d994589ed1, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

type Error_Response struct {
	Status               Error_Status `protobuf:"varint,1,opt,name=status,proto3,enum=fantlab.Error_Status" json:"status,omitempty"`
	Context              string       `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Error_Response) Reset()         { *m = Error_Response{} }
func (m *Error_Response) String() string { return proto.CompactTextString(m) }
func (*Error_Response) ProtoMessage()    {}
func (*Error_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_176b67d994589ed1, []int{0, 0}
}

func (m *Error_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_Response.Unmarshal(m, b)
}
func (m *Error_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_Response.Marshal(b, m, deterministic)
}
func (m *Error_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_Response.Merge(m, src)
}
func (m *Error_Response) XXX_Size() int {
	return xxx_messageInfo_Error_Response.Size(m)
}
func (m *Error_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Error_Response proto.InternalMessageInfo

func (m *Error_Response) GetStatus() Error_Status {
	if m != nil {
		return m.Status
	}
	return Error_UNKNOWN_STATUS
}

func (m *Error_Response) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func init() {
	proto.RegisterEnum("fantlab.Error_Status", Error_Status_name, Error_Status_value)
	proto.RegisterType((*Error)(nil), "fantlab.Error")
	proto.RegisterType((*Error_Response)(nil), "fantlab.Error.Response")
}

func init() { proto.RegisterFile("proto/errors.proto", fileDescriptor_176b67d994589ed1) }

var fileDescriptor_176b67d994589ed1 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xd0, 0xd1, 0x4a, 0xf3, 0x30,
	0x18, 0xc6, 0xf1, 0x2f, 0xfb, 0x5c, 0xb7, 0xbd, 0xb0, 0x91, 0xbd, 0x6c, 0x50, 0x3c, 0x1a, 0x3b,
	0xda, 0x89, 0x1d, 0xe8, 0x15, 0x54, 0x9a, 0xd5, 0xe2, 0x96, 0x48, 0x92, 0x5a, 0xf0, 0x24, 0xb4,
	0x52, 0x8f, 0xa4, 0x09, 0x4d, 0x04, 0x6f, 0xc0, 0x3b, 0xf5, 0x42, 0xc4, 0x3a, 0xf1, 0xf0, 0xe1,
	0xff, 0x3b, 0x7a, 0x00, 0x5d, 0x6f, 0x83, 0xdd, 0xb7, 0x7d, 0x6f, 0x7b, 0x9f, 0x0c, 0x03, 0x27,
	0x2f, 0x75, 0x17, 0x5e, 0xeb, 0x66, 0xfb, 0x49, 0x60, 0xcc, 0xbe, 0xcb, 0xa5, 0x82, 0xa9, 0x6c,
	0xbd, 0xb3, 0x9d, 0x6f, 0xf1, 0x0a, 0x22, 0x1f, 0xea, 0xf0, 0xe6, 0x63, 0xb2, 0x21, 0xbb, 0xc5,
	0xf5, 0x3a, 0x39, 0xfb, 0x64, 0xb0, 0x89, 0x1a, 0xa2, 0x3c, 0x23, 0x8c, 0x61, 0xf2, 0x6c, 0xbb,
	0xd0, 0xbe, 0x87, 0x78, 0xb4, 0x21, 0xbb, 0x99, 0xfc, 0x9d, 0xdb, 0x0f, 0x02, 0xd1, 0x0f, 0x46,
	0x84, 0x45, 0xc9, 0xef, 0xb9, 0xa8, 0xb8, 0x51, 0x3a, 0xd5, 0xa5, 0xa2, 0xff, 0x30, 0x86, 0x95,
	0x12, 0x27, 0xa6, 0xef, 0x0a, 0x9e, 0x9b, 0x8a, 0x71, 0x6d, 0x2a, 0x29, 0x78, 0x4e, 0x09, 0xae,
	0x61, 0x59, 0xf0, 0xc7, 0xf4, 0x58, 0x64, 0xe6, 0x21, 0x95, 0xe9, 0x89, 0x69, 0x26, 0xe9, 0x08,
	0xe7, 0x30, 0xe3, 0x42, 0x9b, 0x83, 0x28, 0x79, 0x46, 0xff, 0xe3, 0x0a, 0xe8, 0x9f, 0x52, 0xaa,
	0x12, 0x32, 0xa3, 0x17, 0xb8, 0x84, 0xf9, 0x51, 0xe4, 0x46, 0x94, 0xda, 0x1c, 0x0a, 0xa9, 0x34,
	0x1d, 0xdf, 0x4e, 0x9f, 0xa2, 0xda, 0xb9, 0xbd, 0x6b, 0x9a, 0x68, 0x38, 0xe0, 0xe6, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0xf0, 0x0b, 0x35, 0x1f, 0x16, 0x01, 0x00, 0x00,
}
