language: go
go:
  - "1.14"
env:
  - GO111MODULE=on
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh
  - mv bin/golangci-lint sources/linter
  - cd sources
  - chmod +x linter
script:
  - ./linter run --verbose --deadline=5m
  - go test ./...
