version: '3.7'

services:
  mc:
    image: memcached
    restart: unless-stopped
    networks:
      - flnetwork
  db:
    image: mariadb
    restart: unless-stopped
    networks:
      - flnetwork
    volumes:
      - flsqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fantlab
      MYSQL_ROOT_PASSWORD: pass
  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - flnetwork
  web:
    build:
      context: ..
    restart: unless-stopped
    depends_on:
      - db
      - mc
    ports:
      - 4242:4242
    networks:
      - flnetwork
    environment:
      PORT: 4242
      DEBUG: 1
      DB_ADDRESS: db:3306
      MC_ADDRESS: mc:11211
      MYSQL_URL: root:pass@tcp(db:3306)/fantlab?charset=utf8&parseTime=True&loc=Europe%2FMoscow
      IMAGES_BASE_URL: https://data.fantlab.ru/images
      SIGN_PUB_KEY: zZFlRP3NxWOiGVi+pSMn5nJCu5PjjsYVnLpxSIV3y2Y= # debug only
      SIGN_PRIV_KEY: IVjLbmNybLI49axLWqA0zecjXjNC8910xQfE2wW224zNkWVE/c3FY6IZWL6lIyfmckK7k+OOxhWcunFIhXfLZg== # debug only
volumes:
  flsqldata:
networks:
  flnetwork:
