version: '3.7'

services:
  web:
    build:
      context: ..
    restart: unless-stopped
    depends_on:
      - db
      - mc
      - rds
    ports:
      - 4242:4242
    networks:
      - flnetwork
    volumes:
      - ${CACHE_DIR}:/cache
      - ${FILES_DIR}:/files
      - ${FORUM_ATTACH_DIR}:/forum_attach
      - ${BLOG_FILES_DIR}:/blog_files
    env_file: app.env
