version: '3.7'

services:
  web:
    build:
      context: ..
    restart: unless-stopped
    depends_on:
      - db
      - mc
      - rds
    ports:
      - 4242:4242
    networks:
      - flnetwork
    volumes:
      - ./cache/:/cache
      - ./public/files/messages/:/forum_attach
    env_file: app.env
