version: '3'

services:
  web:
    build:
      context: ..
    restart: unless-stopped
    depends_on:
      - db
      - mc
      - rds
    ports:
      - 4242:4242
    networks:
      - flnetwork
    env_file: app.env
