version: '3.7'

services:
  mc:
    image: memcached
    restart: unless-stopped
    ports:
      - 11211:11211
    networks:
      - flnetwork
  rds:
    image: redis
    command: redis-server --appendonly yes
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - flnetwork
    volumes:
      - flredis:/data
  db:
    image: mariadb
    restart: unless-stopped
    networks:
      - flnetwork
    ports:
      - 3306:3306
    volumes:
      - flsqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fantlab
      MYSQL_ROOT_PASSWORD: pass
  minio:
    image: minio/minio
    restart: unless-stopped
    networks:
      - flnetwork
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    volumes:
      - flminio:/data
  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - flnetwork
volumes:
  flsqldata:
  flredis:
  flminio:
networks:
  flnetwork:
