version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    networks:
      - flnetwork
    volumes:
      - flsqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fantlab
      MYSQL_ROOT_PASSWORD: pass
  adminer:
    image: adminer
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - flnetwork
  web:
    image: flgo
    restart: always
    depends_on:
      - db
    ports:
      - 4242:4242
    networks:
      - flnetwork
    environment:
      PORT: 4242
      GIN_MODE: debug
      WAIT_FOR_DB: db:3306
      MYSQL_URL: root:pass@tcp(db:3306)/fantlab?charset=utf8&parseTime=True&loc=Europe%2FMoscow
volumes:
  flsqldata:
networks:
  flnetwork:
