version: '3.7'

services:
  minio:
    image: minio/minio
    restart: always
    volumes:
      - miniodata:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server /data
volumes:
  miniodata:
