name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      pass:
        description: 'Docker Hub password (fljenkins)'     
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Hide password
        run: |
          pass=$(jq -r '.inputs.pass' $GITHUB_EVENT_PATH)
          echo "::add-mask::$pass"
          echo "docker_pass=$pass" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: fljenkins
          password: "${{ env.docker_pass }}"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fantlab/go:v${{ github.run_number }}
